### ISSUE TITLE
After drag'n'dropping folder with flac+cue only flac is added to queue

### ISSUE THREAD

**Issue by soredake** [strawberrymusicplayer/strawberry#1428] opened 2024-04-23 15:34 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
After drag'n'dropping folder with flac+cue only flac is added to queue.

**To Reproduce**
Install latest version on Windows, drag'n'drop folder with flac+cue files, only flac will be added, which is incorrect.

**Expected behavior**
.cue should be used and parsed to add tracks to queue.

**Screenshots:**
What I see in strawberry:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/5204968/95457fab-8f3b-45c9-b96b-f9d02369e400)

What I see in aimp:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/5204968/9f4e9f62-9cf1-42e7-8042-0324a53b580a)

**System Information:**
 - Operating system: Windows 11 Pro
 - Strawberry Version: 1.0.23

**Additional context**

**Comment by jonaski** [comment] 2024-04-23 15:43
Cue is only properly supported for songs in the collection.

**Comment by jonaski** [comment] 2024-04-26 15:03
Duplicate of #1105
I suggest to use the collection for CUE, not the file view. Since implementing proper cue handling in the file view involves  scanning directories which is what the collection is supposed to do.

**Closed by jonaski** 2024-04-26 15:03 UTC
