### ISSUE TITLE
"Search for cover for this album", when selected from the library tab, doesn't save the cover

### ISSUE THREAD

**Issue by breversa** [strawberrymusicplayer/strawberry#858] opened 2021-12-27 15:45 UTC
**Describe the bug**
"Search for cover for this album", when selected from the library tab, doesn't save the cover, but does when selected from "modify track description"

**To Reproduce**
Play a track
Go to the "Library" tab
Right-click on the album cover
Select "Search for cover for this album"
Choose a cover
Click "OK"
-> Cover is NOT saved

**Expected behavior**
-> Cover is saved and displayed in the library tab for the current playing track

**Screenshots:**

**System Information:**
 - Operating system: Linux Mint 20.2
 - Strawberry Version: Version 1.0

**Additional context**
1. Searching for cover from a right-click on a track, then "Modify track description" DOES work
2. Buttons/labels are translated by me. They may not correspond 100% to the english ones.

**Comment by jonaski** [comment] 2021-12-27 16:51
There is no library tab and no "Search for cover for this album" anywhere.
Searching and setting a cover manually works fine here.

**Comment by breversa** [comment] 2021-12-27 17:02
That means my translation was not accurate enough.

That what I meant:
![image](https://user-images.githubusercontent.com/2071276/147492535-6fe42f61-545b-4d8b-b409-e180a37acc03.png)

**Comment by jonaski** [comment] 2021-12-27 17:16
There is "search for album covers" if you right click on the album cover, but there is no track description, there artist and album, so I'm still not sure what menu you mean. It works fine here, so it's most likely a permission issue, not a bug.

**Comment by breversa** [comment] 2021-12-29 16:51
Thanks for correcting my translastion, @jonaski :)

Indeed, when I select "search for album covers" from the album cover in the bottom left-hand corner, the cover is not saved properly.

However, when I right-click on a track *in the playlist on the right* (sorry, I should have been cleared) then select "modify track description" then click the "change cover" button, then the cover is eventually saved properly.

**Comment by jonaski** [comment] 2022-01-05 18:11
How do you know that the album cover isn't saved? Can you check if you can find it in `~/.local/share/strawberry/strawberry/collectionalbumcovers/`
What option do you have under Settings / Collection / Saving album covers?

**Comment by breversa** [comment] 2022-01-05 18:22
I have "Save cover as embedded image".

How can I tell the name of the cover in that directory : `~/.local/share/strawberry/strawberry/collectionalbumcovers/` ?

**Comment by jonaski** [comment] 2022-01-06 00:20
I see that there is a problem if you already have an existing "manually set" cover for the songs and then save embedded cover, the manually set cover won't be deleted and "manually set" covers are preferred over automatic ones.
Just to clarify:
"automatic set" covers: picked up by the collection scanner, can be songs from the album directory or embedded covers.
"manually set" covers: covers set when searching, or automatically searching, or manually select by the user in a file dialog.
A workaround is use the tag editor and the "delete cover" feature and save, then all covers associated with those songs will be deleted from disk and unset from the songs. Then use search for covers again and set the cover.

**Comment by jonaski** [comment] 2022-01-06 00:23
I'm not sure if the above is the issue in your case size you are showing a screenshot of an album with an empty cover, but I can't see any other problems, I've tested saving embedded cover for both FLAC, Ogg Vorbis and MP3, all seem to work, found a bug though, it wasn't possible to delete existing covers for Ogg Vorbis, should be fixed now.

**Comment by jonaski** [comment] 2022-01-20 17:19
Closing this, if it's still a problem please provide more info.

**Closed by jonaski** 2022-01-20 17:19 UTC
Labels: need more info
