### ISSUE TITLE
ListenBrainz Scrobbling Fails for Tracks with Multiple Artists

### ISSUE THREAD

**Issue by trincowski** [strawberrymusicplayer/strawberry#1581] opened 2024-10-23 23:00 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
ListenBrainz scrobbling fails when the "MusicBrainz Album Artist Id" or "MusicBrainz Artist Id" has multiple values (multiple artists).

**To Reproduce**
Set the "MusicBrainz Album Artist Id" and "MusicBrainz Artist Id" to  "a4a128ce-d33c-4f23-824b-80b7764b4171 / 208ec32e-f776-4b94-af14-ae97515d7863" and play a song.

**Expected behavior**
Scrobble the song.

**Screenshots:**
![MusicBrainz_Tags](https://github.com/user-attachments/assets/f729407e-9a0f-47dc-bc2b-86b35849f124)

![MusicBrainz_Scrobbling_Bug](https://github.com/user-attachments/assets/3635b975-27dc-4d70-b45f-5126ac2f93b1)

**System Information:**
 - Operating system: Linux Mint 22
 - Strawberry Version: 1.1.3

**Additional context**
- The tracks were tagged with MusicBrainz Picard

- It looks like other projects had the same issue: 
  - https://github.com/jcorporation/myMPD/issues/853
  - https://github.com/lyarenei/jellyfin-plugin-listenbrainz/pull/103
  - https://moisescardona.me/fixing-the-listenbrainz-jellyfin-plugin-to-work-with-multiple-artists/

**Comment by jonaski** [comment] 2024-10-25 21:59
What audio format and type of tags does this occur with?

**Comment by trincowski** [comment] 2024-10-25 22:03
> What audio format and type of tags does this occur with?

With MP3, ID3 v2.4 tags.

**Comment by jonaski** [comment] 2024-11-02 01:12
Can you send me a file which this issue occurs with?

**Comment by jonaski** [comment] 2024-11-08 20:45
I found that Strawberry was ignoring any MBID's with more than one entry, fixed now https://github.com/strawberrymusicplayer/strawberry/commit/904ffb1417893f479852b1464a24134aacc19ad5, however I can't reproduce this issue, maybe your entry saved incorrectly, like a string separated by a specific character instead of a list.

**Comment by trincowski** [comment] 2024-11-09 11:52
> Can you send me a file which this issue occurs with?

Sure, here are two files, one with ID3 vs2.3 and other with ID3 vs2.4. They use different ways of storing those tags.

[Examples.zip](https://github.com/user-attachments/files/17687004/Examples.zip)

**Comment by jonaski** [comment] 2024-11-09 19:13
It's a string separated by slash but spaces in between, if I open it in Picard it suggests correcting it to a list:
![image](https://github.com/user-attachments/assets/0b62a83e-e372-4579-b9d8-9933fc2937c7)

**Closed** 2024-11-09 19:23 UTC

**Comment by trincowski** [comment] 2024-11-10 10:19
Thanks for addressing this so quickly!
