### ISSUE TITLE
Moodbar/track progress bar/track freezes when pausing track

### ISSUE THREAD

**Issue by wuwei7** [strawberrymusicplayer/strawberry#1006] opened 2022-07-26 14:10 UTC
**Describe the bug**
Sometimes when I'm listening to a track and pausing a lot the moodbar/track progress bar freezes. Sometimes it freezes and keeps showing the time it froze at, sometimes it shows 0:00 or a random number. Most of the time the track keeps playing normally but a few times the track has also frozen.

**To Reproduce**
1. Start playing a track
2. Pause it
3. Unpause it
4. Keep pausing it from time to time

**Expected behavior**
The track progress bar or track should not freeze.

**System Information:**
 - Operating system: Kubuntu 22.04
 - Strawberry Version: 1.0.7 (PPA)

**Additional context**
- It happens both with the track progress bar and the moodbar
- This bug didn't start in version 1.0.7. It's been going on for a few versions already

**Comment by jonaski** [comment] 2022-07-26 18:24
When this occurs is it with long songs?

**Comment by wuwei7** [comment] 2022-07-27 19:50
> When this occurs is it with long songs?

Yep, 20-30 minute tracks.

**Comment by wennaspeedy** [comment] 2022-08-12 09:28
I have same issue (no long tracks). Progress bar freeze when pause track and after play it stuck on 0:00.

**Comment by jonaski** [comment] 2022-10-09 19:56
I can't reproduce this. And I don't see anything obvious when looking at the source-code. @buckmelanoma Can you test?

**Comment by rensenware** [comment] 2022-11-09 17:32
I have the same issue and would like to test. What would you like me to do for that? What logs should I get?

**Comment by jonaski** [comment] 2022-11-09 22:07
What OS, what Qt version, and what version of GStreamer?
When it occurs does both the track position, remaining time and track slider stop updating? Does it still show the last remaining values?

The most likely cause is if pipeline initialized is set back to false. In that case the progress would be stuck, and the current position and remaining time would probably be stuck to the last known value for the track position. So not reset to 0:00.
The interesting function is `GstEnginePipeline::StateChangedMessageReceived`, code here: https://github.com/strawberrymusicplayer/strawberry/blob/c16396a690087a5397d9f2fc6bd2922d1ec8edb7/src/engine/gstenginepipeline.cpp#L1238
I added some debug logging here:
https://github.com/strawberrymusicplayer/strawberry/commit/c16396a690087a5397d9f2fc6bd2922d1ec8edb7
With this, you can start strawberry in a terminal window and look for the following line:
`Pipeline initialized: State changed from 2 to 3`.
If the problem occurs after pausing and un-pausing, you can look for the following line `Pipeline uninitialized: State changed from x to x`, the interesting part is the state here. What state here is causing it to "un-initialize".

If the track position is reset to 0:00 and the track slider is also reset, then the above case is unlikely, so it's either the track update timer not correctly starting after un-pausing, or something to do with calculating the track position itself.
This is in the `MainWindow::UpdateTrackSliderPosition` function, specifically this line: https://github.com/strawberrymusicplayer/strawberry/blob/c16396a690087a5397d9f2fc6bd2922d1ec8edb7/src/core/mainwindow.cpp#L1689
But as far as I can tell the only thing we have changed with that code is to switch from a C-style cast to `static_cast`.

**Comment by jonaski** [comment] 2022-12-03 21:35
@wuwei7 @rensenware @wennaspeedy Any more information here?

**Comment by jonaski** [comment] 2022-12-10 17:50
Closing this because of lack of replies here. Can reopen if more information is provided that can be used to fix the bug.

**Closed by jonaski** 2022-12-10 17:50 UTC
Labels: need more info
