### ISSUE TITLE
Unable to play songs from Airsonic

### ISSUE THREAD

**Issue by Superpiffer** [strawberrymusicplayer/strawberry#266] opened 2019-09-20 13:20 UTC
I have an Airsonic server on Docker and I access it from outside via traefik, so my address is: https://airsonic.MYWEBSITE.duckdns.org.
The problem is that even if the test is successful and I can see all the tracks, if I try to play one song I have an error: "Secure connection setup failed."
I'm using the last development version: 0.6.3-79-g2d4efd6

Thanks.

EDIT: with the debug version this is the result:
```
ERROR GstEnginePipeline:659            ErrorMessageReceived 1 "../../../gst-plugins-good-1.16.0/ext/soup/gstsouphttpsrc.c(1380): gst_soup_http_src_parse_status (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:\nTLS/SSL support not available; install glib-networking (6), URL: https://airsonic.***.duckdns.org/rest/stream.view?c=Strawberry&v=1.11.0&f=json&u=***&p=enc%***&id=***, Redirect to: (NULL)"
ERROR GstEnginePipeline:659            ErrorMessageReceived 1 "../../../../gstreamer-1.16.0/libs/gst/base/gstbasesrc.c(3072): gst_base_src_loop (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:\nstreaming stopped, reason error (-5)"
ERROR GstEngine:499                    Gstreamer error: 3870 5 "Secure connection setup failed."
ERROR GstEnginePipeline:659            ErrorMessageReceived 1 "../../../gstreamer-1.16.0/plugins/elements/gsttypefindelement.c(986): gst_type_find_element_chain_do_typefinding (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstTypeFindElement:typefindelement1:\nCan't typefind stream"
```

**Comment by jonaski** [comment] 2019-09-20 15:25
Did you try install glib-networking like it says?
In any case the problem is your libgstsoup plugin. So the correct place to report it is your distro.

**Comment by Superpiffer** [comment] 2019-09-20 15:33
I forgot to mention, the problem occurs on Windows 10 so I don't know how to install such dependencies...

**Comment by jonaski** [comment] 2019-09-21 10:39
Can you try the latest build now and see if it's fixed (0.6.3.84.gf645950).
I tested it now both with Tidal and Airsonic behind apache with HTTPS.

**Comment by Superpiffer** [comment] 2019-09-23 06:51
Perfect, now it works! Thanks! 👍

**Comment by jonaski** [comment] 2019-09-23 14:06
I see, thanks for the investigation, I will fix it

**Comment by Superpiffer** [comment] 2019-10-30 08:22
Sometimes I still have this issue, Strawberry throw the message "Secure connection setup failed.". Deleting the gst registry file (GStreamer cache?), in my case C:\Users\MYUSER\AppData\Local\Strawberry\Strawberry\gst-registry-0.6.5-34-g80ebfbe-bin, solves the problem. There is something you can do?
Thanks.

**Comment by bobberb** [comment] 2020-01-09 03:39
Just encountered this bug, deleting the bin as per @Superpiffer  on windows 10 fixed the issue after version change. Might want to mention this somewhere in the readme @jonaski

**Comment by satcom886** [comment] 2020-04-26 14:50
Just encountered this with a new install of 0.6.9 (on Windows 10). Deleting the `gs-registry` file didn't seem to help. I deleted the entire folder in `AppData/Local/Strawberry` and that solved it. I never had this issue on Linux (Arch).

**Comment by satcom886** [comment] 2020-04-26 16:15
Ok, nevermind. The problem **RETURNS** every time I restart Strawberry. After each restart I have to delete the `gst-registry` file in `AppData/Local/Strawberry`. This is really annoying!

**Comment by jonaski** [comment] 2020-04-26 16:34
Weird. I'll look into it

**Comment by satcom886** [comment] 2020-04-26 16:36
The only thing that I think could be "non-standard" is I installed Strawberry onto a different drive (D:\)

**Comment by jonaski** [comment] 2020-04-27 13:59
I suspect this is a bug in gstreamer. I've made a workaround that automatically deleted the registry file on startup before calling gst_init(), this fixes the problem. Startup might take longer, since it scans for plugins each time you start, but on a modern system with a SSD you can't even notice the difference.

**Comment by satcom886** [comment] 2020-04-29 17:12
Ok, I actually made a `.bat` file that also removes the registry file. Having it in the actual application will be much nicer.

**Comment by jonaski** [comment] 2020-05-01 17:09
I'll leave this open in case someone has a better solution, or the problem is fixed in gstreamer.

**Comment by jonaski** [comment] 2020-06-22 12:22
I'll look into this with the next GStreamer release, the workaround should be enough until then.

**Closed by jonaski** 2020-06-22 12:22 UTC
Labels: bug, confirmed, help wanted
