### ISSUE TITLE
Spanish translation in interface displays "&" symbol within some words

### ISSUE THREAD

**Issue by Moltkex** [strawberrymusicplayer/strawberry#636] opened 2021-01-22 00:11 UTC
**Issue**
In Strawberry's interface, in the side panel, Spanish translation shows the "**&**" symbol within some words.

**To Reproduce**
Install strawberry in a system with Spanish as locale.

**Expected behavior**
Words should show no "**&**" symbol within words.

**Screenshot:**
![image](https://i.imgur.com/geMEN3b.png)

**System Information:**
 - Operating system: Debian 10
 - Strawberry Version: 0.8.5

**Comment by jonaski** [comment] 2021-01-22 01:05
Strawberry does not use any ampersands in the code for the text on these tabs, or in the translated text. So whatever ampersands added, its a bug somewhere else.

Works fine here:

![image](https://user-images.githubusercontent.com/10343810/105431462-f35f0b80-5c55-11eb-8100-1b2335b27f80.png)

No ampersands in our code:

![image](https://user-images.githubusercontent.com/10343810/105431157-60be6c80-5c55-11eb-81f9-b6765fc2d551.png)

No ampersands in translated text for Spanish:

![image](https://user-images.githubusercontent.com/10343810/105431075-37054580-5c55-11eb-8fea-c8d88330e242.png)

If you use KDE, it's a well-known bug. See: https://bugs.kde.org/show_bug.cgi?id=337491
Duplicate of https://github.com/strawberrymusicplayer/strawberry/issues/37 and https://github.com/strawberrymusicplayer/strawberry/issues/99

**Comment by Moltkex** [comment] 2021-01-22 01:24
> If you use KDE, it's a well-known bug. See: https://bugs.kde.org/show_bug.cgi?id=337491
Duplicate of #37 and #99

I do use KDE so that might explain why the ampersands are shown. 
Thanks for the quick reply.

**Closed** 2021-01-22 01:38 UTC
