### ISSUE TITLE
Songs from album doubled in collection

### ISSUE THREAD

**Issue by Meowserita** [strawberrymusicplayer/strawberry#902] opened 2022-02-20 10:41 UTC
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
songs of one specific album are duplicated in strawberry.

**To Reproduce**
this is probably not gonna be possible to duplicate one your end, but for me its as simple as delete the album, refresh collection in strawberry close strawberry, copy DISSIDENTE - ДИССИДЕНТЫ - The War on Two Fronts.zip to my music folder extract the zip, delete the zip and launch strawberry.

**Expected behavior**
expect the album to appear in strawberry with one copy of each song,

**Screenshots:**
![war on two fronts duplicated](https://user-images.githubusercontent.com/99880754/154838394-31f23c96-e38b-4cc2-b8c5-60766661cd89.png)
![war on two fronts files](https://user-images.githubusercontent.com/99880754/154838401-977327b1-7e88-456c-a819-18db9e95354c.png)

**System Information:**
 - Operating system: windows 10
 - Strawberry Version: 1.0.1-89-g604b35df

**Additional context**
this is probably not gonna be possible to reproduce on your end as its literally this one specific zip causing problems, i delete and re add another album (catbite - nice one for context) following the exact same steps and it doesnt duplicate in strawberry. delete and download the problem album off bandcamp and follow the steps and it does duplicate. my best bet is it might be something specific to either the album or the artist possibly the cyrillic in the bands name but that doesnt really make sense to me, so really no clue at all.

**Comment by jonaski** [comment] 2022-02-20 16:25
Is "Song fingerprinting and tracking" on or off in the collection settings?
If it's off, is the "Mark disappeared songs unavailable" on or off?

**Comment by Meowserita** [comment] 2022-02-21 06:48
song fingerprinting and tracking is off and mark disappeared songs unavailable is on.

**Comment by prestidigitonium** [comment] 2022-05-27 20:09
I have the same problem with `song fingerprinting and tracking` on or off and `disappeared songs unavailable` on or off

**Comment by ccritter** [comment] 2022-05-29 16:04
Same issue, Windows 10, Strawberry 1.0.4. Can also provide info if needed.

**Comment by prestidigitonium** [comment] 2022-05-30 10:40
the same problem is also in latest Clementine buld, so I opened an issue in its github repository too

**Comment by jonaski** [comment] 2022-05-30 20:38
If you have more than one file with the same artist, album and song title then it will show two times, that's not a bug (even with fingerprinting on). You could separate them by appending something to one of them album tiles, like expanded, deluxe, etc.

**Comment by prestidigitonium** [comment] 2022-05-30 21:22
Folder name is different, and they are in different paths. Changing the metadata name of the album it's not correct in my opinion because the name of the album shouldn't contain the album flavor ("expanded", "Japanese"), just like MusicBrainz does.
![1](https://user-images.githubusercontent.com/63223659/171059935-c9600c27-7831-43c1-b59d-b8e8835bd413.png)

There are other albums with same album name, same artist and (not all) same songs but in different positions (see screenshot below), that are correctly separated in different albums. Why?
![2](https://user-images.githubusercontent.com/63223659/171059949-c7c55d64-5976-4d07-a9b6-a8735697577f.png)
![image](https://user-images.githubusercontent.com/63223659/171059953-ceebbd7d-2010-4b8e-89d1-1ecbef20e056.png)

Do you know if there are other ways to separate them other than changing metadata?

**Comment by jonaski** [comment] 2022-05-30 21:54
The grouping tag can separate two albums with the same album title, but Strawberry only uses the grouping tag when using year - album (disc) grouping, not sure if I remember why I didn't use the grouping tag for normal album grouping without year. But it has been like that for a long as I can remember. Anyway, this has nothing to do with the original bug which was about a specific album being duplicated in the collection.

**Comment by ccritter** [comment] 2022-06-06 04:30
I just took a look at my DB and for albums that are duplicated, each song in the songs table has two completely identical rows (aside from the ID). I'm not set up with this repo to debug, but if I were, I'd put a breakpoint [here](https://github.com/strawberrymusicplayer/strawberry/blob/6d618c4b78457f8af89fd7663e9f8fb05f3da459/src/collection/collectionbackend.cpp#L652) and take a look at the callstack to see why we're getting here twice. I hit this very very frequently, nearly every album I import gets duplicated:
1. Drag some unimported files into a playlist, maybe have multiple albums as a better test. Not sure if also important, but most of the music I'm importing comes from Bandcamp (you can easily find some free albums to test with)
2. Select all, right click, "Move to Collection"
3. Import them
4. See duplicates in the Collection

Just today I imported 7 albums, and 4.5 of them got duplicated (only half the songs on one was duped).

**Comment by jonaski** [comment] 2022-06-07 20:49
@ccritter That's probably directly related to the organizing, different issue than the original bug report. Even though I could not reproduce it, here is a possible fix https://github.com/strawberrymusicplayer/strawberry/commit/dc1f9edfaf60e51568454ebe9c4e04aacb7f19b7

I could not reproduce the original bug reported to by @Meowserita, even when creating files and tags with the same name.

**Comment by jonaski** [comment] 2022-06-14 17:08
Closing this as I can't reproduce any more issues related to duplicated songs.

**Closed by jonaski** 2022-06-14 17:08 UTC
Labels: need more info

**Comment by manofsticks** [comment] 2023-06-28 02:07
I am also having this issue, but I have not been able to find any rhyme or reason to when/why it happens. In my experience, hitting "organize" a couple times will eventually fix it after 1 or 2 organizes.

**Comment by manofsticks** [comment] 2023-10-15 20:27
This is still a frequent issue I have when using "Move to Collection" from the files tab. My fix is still to do "Organize Files", which seems to (usually) clear it up after the Move. Is there anything I can do to help troubleshoot this?
