### ISSUE TITLE
Inaccessible Albums after adding a second folder of Albums to Music Collection

### ISSUE THREAD

**Issue by Tibokan** [strawberrymusicplayer/strawberry#534] opened 2020-09-05 02:17 UTC
**Describe the bug**
Adding a new set of albums stored in a separate folder to your Strawberry collection using Preferences, will cause a bug to occur, where the new album thumbnails will show up in your collection, with no album image showing and no discs/tracks nested underneath.

When you are loading that same folder for the first time in Strawberry without anything in your collection, this bug does not occur. It only occurs when you are supplementing your music collection with additional folders/albums, particularly those are considered compilations (most reproducible).

This bug resolves itself after a Strawberry restart.

**To Reproduce**
Add one set of compilations from a folder to your music compilation. Expand 'Various artists' and then go to Preferences, and add a second separate folder of compilations to your music compilation. The bug should then be visible/occur.

**Expected behavior**
Strawberry should add the albums to your music collection, display them correctly and allow you to play them without requiring a restart.

**Screenshots:**
Had the 'Annuals' compilations previously added to my Collection - adding 'Sessions' compilations from a second folder causes the bug to occur:
![Screen Shot 2020-09-05 at 12 15 19 pm](https://user-images.githubusercontent.com/69946799/92295826-92b68700-ef71-11ea-9eef-fc8abfb25b98.png)

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.7.2.85 (happens with all Strawberry versions I've tried)

**Additional Context**
Looks like all of the newly added tracks will show up under a single album until you restart Strawberry (in the example discussed above, it is under the first 'Sessions' album in the list, Late Night Sessions, which shows approximately 300-400 tracks sitting underneath it)
![Screen Shot 2020-09-05 at 12 18 43 pm](https://user-images.githubusercontent.com/69946799/92295873-25572600-ef72-11ea-8af3-95d42ca89d48.png)

**Comment by jonaski** [comment] 2020-09-05 12:05
I am unable to reproduce any problems here.
With an empty collection I added one directory mixed compilations, expanded various artists, then added a second directory that also has compilations, it shows up in various artists again fine.
In your case from the albums that can't be expanded, it looks like it wasn't finished updating the collection, although that does not explain 300 sounds under one album, unless the album title actually is the same for all those songs. How long did you wait? There is an indicator on the bottom of the playlist to the left indicating the update status when the collection is updating.

**Comment by Tibokan** [comment] 2020-09-05 12:24
I can reproduce this issue quite consistently, though from additional testing, it could be related to the specific Music Collection view I use:
![Screen Shot 2020-09-05 at 10 17 53 pm](https://user-images.githubusercontent.com/69946799/92304968-2ade5b80-efc6-11ea-8e1d-2e1ad2028215.png)

100% way of reproducing for me:
- Open Strawberry
- Remove an existing folder of Compilation albums using the Preferences pane
- After it has removed, readd the same folder of Compilation albums back
- You should see the glitch shown above

My additional testing has shown that changing the Music Collection view fixes the display/access problem for those albums without needing a Strawberry restart, so it might be a visual glitch only associated with the Music Collection view settings I listed above.

**Comment by jonaski** [comment] 2020-09-05 13:30
I can reproduce it now on macOS but not on Linux.

**Comment by jonaski** [comment] 2020-09-05 15:27
I finally found the problem after 2 hours of debugging. Should be fixed now.

**Closed** 2020-09-05 15:27 UTC
Labels: bug, confirmed

**Comment by Tibokan** [comment] 2020-09-08 00:28
Working beautifully now, thank you so much for your efforts!

**Comment by Tibokan** [comment] 2020-09-08 03:00
I may have jumped the gun a bit there, as I've discovered a sub-bug associated with this - Whilst the albums are now accessible after readding the folder to the music collection, you now only see the first disc (and again, can be manually worked around by changing to a different Music Collection view and then changing back, or restarting Strawberry). Please see screenshot below:
![Screen Shot 2020-09-08 at 12 56 50 pm](https://user-images.githubusercontent.com/69946799/92428651-0905f400-f1d3-11ea-9f8b-fc3d483bfbc6.png)

My guess is that the code adjustment you made for 'Year - Album' may also need to be applied for 'Disc'.

**Comment by Tibokan** [comment] 2020-09-12 04:07
Problem solved with your collection coding overhaul, fantastic work @jonaski !
