### ISSUE TITLE
Set saved Playlist to favourite Playlist don`t work

### ISSUE THREAD

**Issue by ukdevel** [strawberrymusicplayer/strawberry#745] opened 2021-08-11 20:58 UTC
Klicking a star with only one loaded Playlist is not possible.
If you load a second Playlist, Star can be clicked and add Playlist to favourite, but when Playlist is cleared, clicking on favourite Playlist has no effect.
Strawberry 0.9.7 at Ubuntu 20.04 LTS
installed with:
strawberry_0.9.3-focal_amd64.deb

**Comment by jonaski** [comment] 2021-08-11 21:35
Clicking star isn't possible when only one playlist is open, the last playlist is never lost then anyway, and you can simply open 2 playlists if you want the tabs and the ability to favorite it. This has been asked before, I decided not to change anything about it then, and I haven't changed my mind.
But it should be possible to favorite a playlist independent of whether it is empty or not, there is nothing in the code that explains that it isn't possible, and it works fine for me here.

**Comment by jonaski** [comment] 2021-08-16 18:47
Closing this as I can't reproduce the issue with staring a playlist not having effect.

**Closed by jonaski** 2021-08-16 18:47 UTC
