### ISSUE TITLE
Smart playlists

### ISSUE THREAD

**Issue by liftarn** [strawberrymusicplayer/strawberry#264] opened 2019-09-19 08:38 UTC
In Clementine there is smart playlists so so you can for instance create a playlist with tracks you haven't listened to. Strawberry don't have this function and it's very nice to have.

**Comment by jolugaju** [comment] 2019-10-02 06:21
It would be great to have this option.

**Comment by githubjsorg** [comment] 2019-10-24 18:54
I agree. This was one of the biggest disappointments when I was forced to migrate from Clementine to Strawberry due to the former not working on Mojave at all.

Since Strawberry is a fork of Clementine after Clementine was no longer being updated, I don't see how this isn't already in Strawberry. Was it removed? If so, why?

**Comment by jonaski** [comment] 2019-10-24 19:01
I removed it because of some bugs, basically it's too unstable (crashing). I looked into it recently and found that the crash is related to the preview part in the wizard where it uses a playlist model/view to display the result, it took a lot of time to debug it, because the crash occurs when returning to the main loop and is not obvious to figure out. I will look into it again when I get some more free time.

**Comment by githubjsorg** [comment] 2019-10-28 16:52
Hi jonaski,

Thanks for your reply. I don't know what instability you were seeing as I have never had an issue with that in Clementine. Please let me know if I can help with testing.

**Comment by jonaski** [comment] 2019-10-28 19:18
If you create 2 new smart playlists, it usually crashes on the second. Happens in Clementine both with the qt4 and the qt5 version.
Does it work for you?

**Comment by githubjsorg** [comment] 2019-10-29 03:39
I never created any smart playlists, I only ever used the pre-packaged ones. Mostly the "All tracks" one.

**Comment by liftarn** [comment] 2019-10-31 11:51
I have made a "Dynamic never played" smart playlist that is very handy when you add new music to your library.

**Comment by AryToNeX** [comment] 2019-12-25 02:35
+1 for this feature. It would be nice to have it back, since this is a Clementine fork.

**Comment by mha-k** [comment] 2020-03-05 18:34
I second this feature request. I just switched from Clementine to Strawberry for bit perfect audio. The only thing I miss are dynamic playlists and an option to export and import them.

**Comment by meeotch** [comment] 2020-04-27 16:54
+1 for smart playlists.  It's the single thing preventing me from switching from Clementine.  I have a single smart playlist that encompasses my entire collection, which I use pretty much exclusively.  Basically, I'm in "smart shuffle" mode all the time.

Never had a problem with crashes - though I'm not creating new smart playlists all the time.  Willing to try and reproduce the crashes you've seen, though, if you can provide instructions.

**Comment by jonaski** [comment] 2020-04-28 15:07
The crash is fixed. But there are some other minor issues. The whole thing is in the smartplaylists branch if someone wants to help with it. I have just merged the branch with master and tested it.

- The tabbar needs to be fixed so it works with longer text "smart playlists", either the text needs to wrap, or the tabbar needs to be a little wider.
- The smart playlists view should have some buttons on top to maintain smart playlists (like in the files and playlists view).
- All the new code should be reviewed.
- Everything needs to be tested.
- We might want to consider adding ratings at the same time so we don't have to do a separate schema update later for that.

![image](https://user-images.githubusercontent.com/10343810/80503282-ec7ac500-8971-11ea-8aad-0615bdb4c565.png)

**Comment by desputinski** [comment] 2020-05-03 12:54
>     * We might want to consider adding ratings at the same time so we don't have to do a separate schema update later for that.

Oh, that would be fantastic! Rating is the main reason why I'm currently also still using clementine parallel to strawberry

**Comment by b4n4n4p4nd4** [comment] 2020-05-09 01:06
Smart playlist for "never played" can be done with regular playlist using play-count column sorted ascending. Only caveat being when you add new music you have to manually add it to the playlist and re-sort, and sort again when resuming if you lose your spot. Not as automatic as I'd like, but it works for me for now.

**Comment by jonaski** [comment] 2020-08-25 18:28
I have posted an update on Strawberry in #259 and on the forum.

**Closed** 2020-09-17 15:51 UTC
Labels: enhancement

**Comment by jonaski** [comment] 2020-10-03 14:13
I made a list of things to test here: https://forum.strawberrymusicplayer.org/topic/89/testers-needed-before-new-release

**Comment by JohnOShock** [comment] 2021-02-13 13:36
> In Clementine there is smart playlists so so you can for instance create a playlist with tracks you haven't listened to. Strawberry don't have this function and it's very nice to have.

It does now and works great! :)
