### ISSUE TITLE
Global media shortcuts don't work with KGlobalAccel

### ISSUE THREAD

**Issue by DarthGandalf** [strawberrymusicplayer/strawberry#849] opened 2021-12-06 12:01 UTC
**Describe the bug**
I tried to configure global keyboard shortcut for Play/Pause. But it does nothing when pressed.

I checked in KDE settings, and it recognized Strawberry, but has only 2 shortcuts instead. These 2 shortcuts work, the other don't.

**To Reproduce**
Every time. I even tried to remove strawberry shortcuts from kde settings, and upon startup, it creates only these 2.

**Expected behavior**
When I press the key, the action should happen. This was working fine with Clementine.

**Screenshots:**

![Настройки_246](https://user-images.githubusercontent.com/325092/144841711-07760c85-3f74-4fd9-a056-96e8e545c032.png)

![Комбинации клавиш  — Параметры системы_001](https://user-images.githubusercontent.com/325092/144841822-f92b918b-ccf0-49a3-a941-9e0769715cb9.png)

**System Information:**
 - Operating system: Gentoo Linux, KDE Plasma, kernel 5.10.68-x86_64
 - Strawberry Version: 1.0.0-125-g4c6251bf

**Additional context**

**Comment by jonaski** [comment] 2021-12-06 16:38
Media shortcuts play/stop/next/previous are hard-coded to their respective media keyboard shortcuts when using kglobalaccel.
Only the other actions can be assigned a different key from within strawberry.
Maybe the media shortcuts can be changed within KDE settings (I'm not sure). The other alternative is to use X11 shortcuts.
I can fix so that the media shortcuts are grayed out in the strawberry settings when kglobalaccel is checked, since setting them there have no affect.

**Comment by DarthGandalf** [comment] 2021-12-06 16:51
Thanks for answer.

How does it work for Clementine then? I even want the usual Play/Pause key to be used for Play/Pause. It doesn't work with X11 either (and X11 is not recommended, according to settings), simply nothing happens when I press the key.

I started Clementine back, enabled the Play/Pause key from there, and it's visible and configurable from KDE settings fine:
![Комбинации клавиш  — Параметры системы_002](https://user-images.githubusercontent.com/325092/144887336-37d6d77d-a9a0-4c41-8c1e-f3f9878b3081.png), and it works.

One difference I see is that Clementine is in Applications, while Strawberry is in "System services"(?), not sure whether it matters

**Comment by gerion0** [comment] 2021-12-07 00:22
Everything is working fine for me with Strawberry/KDE/Gentoo. The communication happens via MPRIS. Is Strawberry recognized as player within KDE for you?

![image](https://user-images.githubusercontent.com/32870336/144942994-20dfdedd-9f44-4a0f-9990-0be9260fa6ad.png)

There is also a Global Shortcuts section within Strawberry itself, where you can choose the method that is used.

**Comment by DarthGandalf** [comment] 2021-12-07 01:16
Yes, it's recognized. I see the same popup, and qdbus command returns Paused or Playing. Just the keyboard shortcut doesn't work.

**Comment by DarthGandalf** [comment] 2021-12-07 01:47
> There is also a Global Shortcuts section within Strawberry itself, where you can choose the method that is used.

That's where I have the shortcut set, yes. See my first screenshot.

**Comment by DarthGandalf** [comment] 2021-12-07 11:17
No. I don't want the media keys to affect any random player it founds, like VLC if I am watching something, or Firefox if I have Youtube opened in one of tabs. I want the media keys to affect specifically Strawberry, which is why I'm trying to configure it in Strawberry settings. And the Strawberry settings claim that it's assigned.

**Comment by DarthGandalf** [comment] 2021-12-07 11:30
@gerion0 in your screenshot I noticed that Strawberry is also in Apps like my Clementine is, not in System Services like my Strawberry is. I wonder what caused the difference

**Comment by gerion0** [comment] 2021-12-07 13:22
> No. I don't want the media keys to affect any random player it found, like VLC if I am watching something, or Firefox if I have Youtube opened in one of tabs. I want the media keys to affect specifically Strawberry, which is why I'm trying to configure it in Strawberry settings. And the Strawberry settings claim that it's assigned.

Ok, but then the MPRIS (aka KDE/KGlobalaccel) is not the correct way for you to control Strawberry, isn't it? The whole purpose of the MPRIS controls is that multiple players can be controlled with the same mechanism. Of course, KDE itself can provide a setting to "pin" the shortcuts to one specific player (like it also displays several tabs for several player in the media control widget).

> @gerion0 in your screenshot I noticed that Strawberry is also in Apps like my Clementine is, not in System Services like my Strawberry is. I wonder what caused the difference

I'm not sure. I have also more controls
![image](https://user-images.githubusercontent.com/32870336/145036800-da523ce5-cf65-47d8-a413-4472888fe3a5.png)

**Comment by DarthGandalf** [comment] 2021-12-07 13:30
> Ok, but then the MPRIS (aka KDE/KGlobalaccel) is not the correct way for you to control Strawberry, isn't it?

I don't particularly care about MPRIS, but KGlobalaccel is not limited to Media Players, it's just an API for applications to have a global shortcut.

> I'm not sure. I have also more controls

Yep! These are the exact controls which I'm missing. And I see them for Clementine (when they are set in Clementine settings)

**Comment by jonaski** [comment] 2021-12-12 03:05
I can reproduce this, same problem with the 0.9.3, so I don't know when this stopped working.

**Comment by jonaski** [comment] 2022-01-02 16:04
This seem to be resolved with https://github.com/strawberrymusicplayer/strawberry/commit/bbd81e7d9c248d406cb425966578b6da961f9b3c where I enabled registering of media shortcuts too.

```
17:02:38.657 DEBUG GlobalShortcutsBackendKDE:73     Registering
17:02:38.658 INFO  GlobalShortcutsBackendKDE:158    Registered shortcut "next_track" QKeySequence("Media Next")
17:02:38.658 INFO  GlobalShortcutsBackendKDE:158    Registered shortcut "play_pause" QKeySequence("Media Play")
17:02:38.659 INFO  GlobalShortcutsBackendKDE:158    Registered shortcut "prev_track" QKeySequence("Media Previous")
17:02:38.659 INFO  GlobalShortcutsBackendKDE:158    Registered shortcut "stop" QKeySequence("Media Stop")
```

**Closed by jonaski** 2022-01-02 16:04 UTC
Labels: bug, confirmed
