### ISSUE TITLE
Songs doubled in player

### ISSUE THREAD

**Issue by niboe-boop** [strawberrymusicplayer/strawberry#860] opened 2021-12-30 17:43 UTC
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Each song in a particular album is doubled in the program. For each file in my folder, that song appears twice.

**To Reproduce**
type this command into youtube-dl:
> youtube-dl -f bestaudio https://ex-lyd.bandcamp.com/album/space

Put the songs in a new folder named "space" and put that folder in a new folder named "EX-LYD" (these are album and artist names)

Put the EX-LYD folder into your music directory for Strawberry

The songs may not show as doubled until you restart Strawberry Music Player

**Expected behavior**
Each audio file should have one track in Strawberry

**Screenshots:**
![image](https://user-images.githubusercontent.com/76244859/147774592-77ad3faa-6dbc-4aa1-916c-23d306a4e2c5.png)
![image](https://user-images.githubusercontent.com/76244859/147774652-096bf6e6-cf56-45fe-a6ab-b4350c27019d.png)

**System Information:**
 - Operating system: 
Edition	Windows 10 Pro
Version	20H2
OS build	19042.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

 - Strawberry Version: 1.0

**Additional context**
youtube-dl version: 2021.06.06
Since I don't have this issue with any other songs, I suspect the issue is in the downloaded files.

**Comment by jonaski** [comment] 2022-01-01 00:42
I found an ugly bug where it wasn't updating the file path when songs were moved on disk, it was only working when the album had a cover in the album directory, that's why I've overlooked it when testing previously.
Should be fixed https://github.com/strawberrymusicplayer/strawberry/commit/004d219c9723b0f4e66f30fd1d41ee53e9f33c6e
It's possible that this that bug was causing the duplicates in your case, at least I can't reproduce any bugs related to duplicates on either Linux or Windows.

**Comment by jonaski** [comment] 2022-01-01 00:45
You probably have to manually remove the duplicates as I don't think it will recover from it by itself, easiest is to just remove the songs and do a re-scan.
Use Tools / Console and the command:
`DELETE FROM songs WHERE album = 'Space';`

**Closed by jonaski** 2022-01-01 00:45 UTC
