### ISSUE TITLE
Keep running in the background when the window is closed causes exit with Wayland

### ISSUE THREAD

**Issue by userofryzen** [strawberrymusicplayer/strawberry#964] opened 2022-05-18 17:18 UTC
For technical issues, questions and discussion please use the forum on https://forum.strawberrymusicplayer.org/
Any issues related to feature requests will be closed. See the README for more details.

Check the Changelog to see if the issue is already fixed: No fixed
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
When i hit close buttom strawberry doesn't go to tray, it will close.

**To Reproduce**
At least my system is manjaro, with plasma and wayland session, everything updated. Before it was working correct I think..

**Expected behavior**
When I press close buttom strawberry must go to tray if the option is enabled. 

**System Information:**
 - Operating system: Manjaro stable
 - Strawberry Version:1.0.4-2

**Additional context**
I think is a regression because before it was working well.. Maybe strawberry compiled with latest qt version makes unusable close to tray?

Globalmenu is broken too with wayland

**Comment by jonaski** [comment] 2022-05-18 17:34
Start strawberry from the terminal and see if there is a error message, or the close event resulting in a crash. if so do a gdb backtrace: https://github.com/strawberrymusicplayer/strawberry/wiki/Backtrace

**Comment by userofryzen** [comment] 2022-05-18 17:46
> Start strawberry from the terminal and see if there is a error message, or the close event resulting in a crash. if so do a gdb backtrace: https://github.com/strawberrymusicplayer/strawberry/wiki/Backtrace

19:45:37.325 DEBUG SCollection:158                  CollectionBackend(0x5598a50fa780) successfully exited.
19:45:37.325 DEBUG Application:304                  PlaylistBackend(0x5598a5c93dc0) successfully exited.
19:45:37.325 DEBUG Application:304                  TagReaderClient(0x5598a51a6da0) successfully exited.
19:45:37.325 DEBUG DeviceManager:215                GioLister(0x5598a5becdd0) successfully closed.
19:45:37.325 DEBUG Application:304                  AlbumCoverLoader(0x5598a5174e10) successfully exited.
19:45:37.325 DEBUG TidalService:240                 CollectionBackend(0x5598a55988f0) successfully exited.
19:45:37.325 DEBUG TidalService:240                 CollectionBackend(0x5598a54b7650) successfully exited.
19:45:37.325 DEBUG DeviceManager:215                CddaLister(0x5598a548f980) successfully closed.
19:45:37.325 DEBUG TidalService:240                 CollectionBackend(0x5598a50e7e30) successfully exited.
19:45:37.325 DEBUG DeviceManager:215                Udisks2Lister(0x5598a5bec1d0) successfully closed.
19:45:37.325 DEBUG QobuzService:217                 CollectionBackend(0x5598a54cba60) successfully exited.
19:45:37.325 DEBUG QobuzService:217                 CollectionBackend(0x5598a54cbb00) successfully exited.
19:45:37.325 DEBUG QobuzService:217                 CollectionBackend(0x5598a553c330) successfully exited.
19:45:37.325 DEBUG Application:304                  InternetServices(0x5598a5511090) successfully exited.
19:45:37.325 DEBUG Application:304                  RadioBackend(0x5598a5ccede0) successfully exited.
19:45:37.325 DEBUG SCollection:158                  CollectionWatcher(0x5598a5166400) successfully exited.
19:45:37.325 DEBUG Application:304                  SCollection(0x5598a50e7870) successfully exited.
19:45:37.325 DEBUG DeviceManager:203                DeviceDatabaseBackend(0x5598a5be8ab0) successfully closed.
19:45:37.325 DEBUG Application:304                  DeviceManager(0x5598a5bea580) successfully exited.
19:45:37.326 DEBUG GlobalShortcutsBackendX11:81     Unregistering
19:45:37.497 DEBUG CoverProviders:130               Unregistered cover provider "Tidal"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "Discogs"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "Musixmatch"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "Last.fm"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "Spotify"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "Deezer"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "Qobuz"
19:45:37.498 DEBUG CoverProviders:130               Unregistered cover provider "MusicBrainz"
19:45:37.498 DEBUG LyricsProviders:129              Unregistered lyrics provider "Genius"
19:45:37.498 DEBUG LyricsProviders:129              Unregistered lyrics provider "AudD"
19:45:37.498 DEBUG LyricsProviders:129              Unregistered lyrics provider "Lyrics.ovh"
19:45:37.498 DEBUG LyricsProviders:129              Unregistered lyrics provider "LoloLyrics"
19:45:37.498 DEBUG LyricsProviders:129              Unregistered lyrics provider "Musixmatch"
19:45:37.498 DEBUG LyricsProviders:129              Unregistered lyrics provider "ChartLyrics"

any error at all.. at least I cant see any

**Comment by jonaski** [comment] 2022-05-18 17:51
OK, it works for me but I use X11, I'm guessing it's specific to wayland

**Comment by userofryzen** [comment] 2022-05-18 17:54
> OK, it works for me but I use X11, I'm guessing it's specific to wayland

https://www.mail-archive.com/kde-bugs-dist@kde.org/msg638225.html

okey, the another issue I said it's that, it's with QT6 packages, so.. I think i'm going to put in contact with mantainer of strawberry and Qbittorrent( another app that has the same problem) to see its can be compiled with QT5 until there are fixes in that

But the thing of closing.. Idk if it can be solver by the same thing. 
I have not tested on xorg, wait a moment

**Comment by jonaski** [comment] 2022-05-18 18:01
Switching to Qt 5 is not a good idea since the Qt 5 branches are closed by Qt for commercial users only, we (open source contributors) can't see what's going on or really participate in the development of Qt 5 anymore, so it's much better to try and fix the problem in Qt 6.

**Comment by userofryzen** [comment] 2022-05-18 18:11
> Switching to Qt 5 is not a good idea since the Qt 5 branches are closed by Qt for commercial users only, we (open source contributors) can't see what's going on or really participate in the development of Qt 5 anymore, so it's much better to try and fix the problem in Qt 6.

okey, yeah, all problems was gone using xorg. 
Strawberry works fine, qbittorrent the same, globalmenu.. included Uget that has no tray icon at all.. -.- 

So.. now what? filling a bug in qt 6 or what?

May be I have to put in the issue that wayland +QT6 affects too to the globalmenu feature( it's not showed)

**Comment by userofryzen** [comment] 2022-05-18 19:09
@jonaski have i to fill another bug for the problem of the global/app menu?

another "problem" because Idk if its a regression or not it's that if the windows is not active the systray icon can't "close" to tray but when the window is active yeah( it's the workaround to do the close to tray without the close buttom)
at this way I am giving more info about the problem I think

**Comment by jonaski** [comment] 2022-05-18 21:03
The KDE globalmenu not working with Strawberry is because KDE is still Qt 5, you need to wait until a Qt 6 version of KDE.
If other Qt 6 programs has the same issue with exiting instead of minimizing to system tray, then that bug is probably in Qt.
When opening a bug report in Qt you usually have to provide a minimal code example that reproduces the issue.

**Comment by userofryzen** [comment] 2022-05-19 14:27
then, what to do now?

**Comment by jonaski** [comment] 2022-05-21 16:04
I can confirm the issue on openSUSE Tumbleweed with wayland and KDE.
Looks like the bug is in Strawberry, Strawberry probably incorrectly calls `hide()` when the window closes.

**Closed** 2022-05-21 17:13 UTC
Labels: bug, confirmed

**Comment by userofryzen** [comment] 2022-05-21 18:48
i cant test it right now, have you tested it?

**Comment by userofryzen** [comment] 2022-05-22 19:13
> I can confirm the issue on openSUSE Tumbleweed with wayland and KDE. Looks like the bug is in Strawberry, Strawberry probably incorrectly calls `hide()` when the window closes.

with that is fixed the close to tray thing but not the globalmenu ones, right?

**Comment by jonaski** [comment] 2022-05-22 19:16
Yes, what actual fixed closing to tray was removing the QEvent::spontaneous check commit https://github.com/strawberrymusicplayer/strawberry/commit/36eb13128974d4f7922cbb54c7da65c526ec9618
But I did code improvements too.

**Comment by userofryzen** [comment] 2022-05-22 23:25
> Yes, what actual fixed closing to tray was removing the QEvent::spontaneous check commit [36eb131](https://github.com/strawberrymusicplayer/strawberry/commit/36eb13128974d4f7922cbb54c7da65c526ec9618) But I did code improvements too.

so.. making another bug for the globalmenu ones problem or have you reported it to Qt or something?

**Comment by userofryzen** [comment] 2022-10-11 06:58
May be is It posible to ignore It when the option close to tray is enabled
? If there is need to be closed I think it can be managed to not ignore the
close event if the window is on tray!
For me qbittorrent the only problem that has is the globalmenu but not any
more .
Is it possible to fix then?
