### ISSUE TITLE
Cannot quite after closing main window on OSX

### ISSUE THREAD

**Issue by monochromec** [strawberrymusicplayer/strawberry#1050] opened 2022-10-04 22:16 UTC
**Describe the bug**
After closing the main window with CMD-w, the quit option in the main  pull-down menu is grayed out and CMD-q doesn't work anymore and the application has to be killed via the Activity Monitor or command line.

**To Reproduce**
Start the player on OSX and close the main window.

**Expected behavior**
Application exits.

**System Information:**
 - Operating system:  OSX Monterey on Apple Silicon
 - Strawberry Version: 1.0.9

**Additional context**
Is this intended behaviour? More than happy to provide additional info as required - just let me know.

**Comment by clementine-user** [comment] 2022-10-05 01:10
Confirmed in strawberry-1.0.9.28.g5c8e4929-x86_64 on macOS 12.7. OP, Control-click, right-click, or two finger tap on the icon in the Dock and select 'Quit' from the popup menu.

**Comment by jonaski** [comment] 2022-11-09 22:14
I can't reproduce this on macOS Big Sur, maybe it's specific Monterey.

**Comment by clementine-user** [comment] 2022-11-11 05:08
@jonaski,

The other fruit-based player, clementine-1.4.0rc1-864-g0fab61278, behaves like this:

Close main playlist window with the red close window button and the app quits.

Closing the main playlist window with Command + W and the app continues to run but the File > Quit command is greyed-out. Clicking on the icon in the dock restores the main playlist window and the app can be closed from keyboard or menu. When the main playlist window is closed with Command + W, Control-clicking, right-clicking, or two finger tapping on the icon in the Dock and selecting 'Quit' from the popup menu allows the app to be quit.

Our favorite music player, strawberry-1.0.10.15.gbb18af09-x86_64, behaves in the exact same way.

The behavior is the same on macOS 10.15.7, macOS 11.7.1, and macOS 12.6.1. This was not tested on macOS 13.0 as it is too new for production.

Strawberry seems to be working as designed so this issue probably can be closed.

**Closed** 2022-11-23 19:24 UTC
