### ISSUE TITLE
Unable to log in to TIDAL

### ISSUE THREAD

**Issue by dc740** [strawberrymusicplayer/strawberry#369] opened 2020-02-15 22:18 UTC
**Describe the bug**
Enabled OAuth (AFAIK the only valid method for new logins), entered a client ID from my browser (looks like a 16 chars token, no need to give details), and clicked on log in.  First the client_id was NOT being set. So I clicked Apply, and then hit login again. Now the Client_id is correctly set in the url in the browser, but I still get `Something went wrong, please try again` from Tidal side and I can't log in
I also tried being logged out from the browser, and I still get the same error.

**To Reproduce**

1. Enable TIDAL
2. Select `Use OAuth`
3. Set the `Client ID`
4. Click Apply
5. Click on Log in

**Expected behavior**
You should be redirected to the login page, or a page to accept the log in from the new device.

**Screenshots:**
![image](https://user-images.githubusercontent.com/546408/74595943-daea7800-5026-11ea-84ad-79ac297b25c2.png)

**System Information:**
 - Operating system: Ubuntu
 - Strawberry Version: master branch

**Additional context**

If I set an invalid cliend ID (just for testing, I set it to the client_unique_key UUID) then I get a different error "Your OAuth2 client configuration is not correct. Please check with TIDAL Partner Support."
So this leads me to believe the client ID is actually correct, but there is something missing in the parameters.

**Comment by gazny** [comment] 2020-02-18 01:32
Similar results for me, I only am able to workaround login my using my username and password.

**Comment by jonaski** [comment] 2020-02-21 21:56
This probably can't be fixed as we don't have access to the API documentation or Tidal partnership.

**Comment by Fef0** [comment] 2020-02-22 01:15
Can totally reproduce, but I can't actually login neither with username and password. Probably a Tidal-related issue, since I can't login from the website either, hope they'll fix it ASAP.

**Comment by gazny** [comment] 2020-02-24 17:27
Tested on fedora 31, similar results. Worked on Pop Os.

**Comment by jonaski** [comment] 2020-02-25 00:32
The response from https://api.tidalhifi.com/v1/login/username is:

`{"status":405,"subStatus":1003,"userMessage":"Method not allowed"}`

They discontinued the login method, that's all. It works if your already have a valid session (logged in), but no new logins are accepted.

**Comment by RomanHargrave** [comment] 2020-02-28 20:47
@jonaski how was it determined that the method was actually discontinued? I have a JS application based on TidalPromise that is able to touch that endpoint and get a new, valid, session without issue. Are we sure it's not just a single client ID?

**Comment by jonaski** [comment] 2020-02-28 21:13
Based on the info @dc740 gave that OAuth is the only mehod (and it won't work since streams are encrypted anyway), I also tested myself with several tokens and could not login with any of them. Several other users reported the same for over a week.
However I tested even more now, and I can confirm that I can login with 3 of the ones listed here: https://gist.github.com/artworked/3003fa0183b464a0b0d2ca2e77afe477
The question is, how long do these last? According to inside info from the MPD people, they are phasing out this login method altogether. Also, I actually have to pay for a subscription to be able to fix streaming issues whenever someone reports it.
The OAuth method for login worked when I implemented it using the official Windows client id, but I could still not stream because the streams were encrypted.
I put a lot of work into both Tidal, Deezer and Qobuz implementations so I'm sad that I had to remove them all, but even if Tidal could work a while longer with some different tokens I'm not sure how long they would last, and all them have declined my request for official access to their API.

**Comment by RomanHargrave** [comment] 2020-02-28 21:44
I suspect that Tidal may change the login system eventually, seeing as the MPD people suggest as much; however, I don't think they're likely to change the rest of the API as their partners have come to depend on it in its current state. They may start to require stream encryption, if anything (this is already enabled on certain tokens).

Until Tidal requires you to run a line to your house to listen to music, they'll always have a client that can be used as a reference for how to decode music from their service.

Adapting to a new login system should not be terribly complex. The absolute worst I can see happening is client certificates and request signing. Something like that would take very little time to extract and then work on implementing a client could start - an effort I don't foresee as being too complicated either and is something I may be willing to work on (I'm always down for taking apart software).

**Comment by jonaski** [comment] 2020-03-07 14:48
We can add Tidal to a separate branch so we can experiment with it

**Comment by Yethal** [comment] 2020-03-09 08:41
@jonaski I have a free slot in my Tidal family plan if you need an account for testing.

**Comment by jonaski** [comment] 2020-04-12 01:29
@Yethal I'm working on testing it out on a different branch, you can add my e-mail adresse listed on my profile if it's possible.  I didn't find your contact info.

**Comment by jonaski** [comment] 2020-04-13 21:29
I added Tidal back since I got a subscription now and can debug things. It seem to work with some of the token using the old method, but I don't know how long.
@RomanHargrave OAuth is already implemented, but you can look into it if it's broken or if it's possible to use it with a app id where the streams aren't encrypted, or perhaps decrypting the streams.

**Comment by jonaski** [comment] 2020-05-13 20:07
I found a bug where it was not sending the client id in the parameters unless you applied the settings first. Fixed now. I also implemented login refresh now. So OAuth fully works.
Everything works through the API using OAuth except for steaming. The problem is that the streams are encrypted. So unless someone can fix that we will eventually just have to remove the streaming and just use Tidal for album covers.

**Comment by mroovaa** [comment] 2020-05-15 15:12
Some time ago I checked RedSea and it worked - according to the terminal output it was able to decrypt the files. Maybe part of the code could be useful?

https://github.com/Azalius/RedSea

**Comment by gfx1** [comment] 2020-05-30 20:29
.

**Comment by jonaski** [comment] 2020-06-22 13:17
It shows what encryption is used (AES CBC), other than that the code is in Python so not very useful to Strawberry.

**Comment by jonaski** [comment] 2020-08-18 17:52
Use this python script to extract a client id from a android APK file:
https://github.com/FUFRUnidentifiedFLACRipper/python-tidal-async-oauth2
Tested here now, works fine.

**Closed by jonaski** 2020-08-18 17:52 UTC

**Comment by Stephan-C** [comment] 2021-12-18 11:09
This is broken again. If you go to this link, it redirects to the new format Tidal is using for the oath link: https://my.tidal.com/grantaccess/oauth

Looks like the redirect_uri generated by Strawberry is what is causing it to fail.

**Comment by jonaski** [comment] 2021-12-18 11:29
Works fine here
