### ISSUE TITLE
(macOS) Performance: constant high CPU usage

### ISSUE THREAD

**Issue by foss-** [strawberrymusicplayer/strawberry#829] opened 2021-11-13 16:58 UTC
**System Information:**
 - Operating system: macOS 11.6.1
 - Strawberry Version: Open Strawberry Version 1.0.0-116-g0fbe5d88

Constant high CPU usage on macOS.

**To Reproduce**
With Strawberry open and doing nothing (no scrolling or playing a track or any interaction at all) Strawberry constantly sits at over 40% CPU usage
<img width="447" alt="Screenshot 2021-11-13 at 17 46 43" src="https://user-images.githubusercontent.com/5708172/141651984-e58edb63-bb9a-4dba-88d3-0e70b9d6ce40.png">

Playing a track it sits at over 60% while sometimes spiking at over 100%:
<img width="428" alt="Screenshot 2021-11-13 at 17 50 27" src="https://user-images.githubusercontent.com/5708172/141652061-cbce72c6-a1c0-412e-99bc-fd73d1fb1d25.png">

**Expected behavior**
CPU usage is too high. Comparing with Apples music app which sits at 0,1% when idle and goes up to under 2% when playing a track.

**Additional context**
Spin Dump: https://bin.disroot.org/?73b77829f80a251e#5vwiHDcJRRTccyUMsLmNgUidDriH9xRhv6HMAEW8hoUn
Process Sample: https://bin.disroot.org/?103ce9f6c263e0fb#HzSkmVV7rWMBXs5GyL1nzbP6h6cA92XRhmUJc6ATSDKw

**Comment by jonaski** [comment] 2021-11-19 21:44
Is this Intel based mac or M1?

**Comment by jonaski** [comment] 2021-12-01 20:00
Uses 15-20% CPU here in my macOS VM.
Did you change any specific configuration options?
Did you try with a fresh configuration? delete ~/Library/Preferences/org.strawberrymusicplayer.Strawberry.plist

**Comment by foss-** [comment] 2021-12-01 21:05
Interesting finding and thanks for going through the effort to verify this problem. Are you also running macOS 11?
I enabled storing metadata back to files and disabled the default library background picture. Other than that can't recall changes.

I removed ` ~/Library/Preferences/org.strawberrymusicplayer.Strawberry.plist` as suggested, installed latest main build.

CPU consumption while playing a track is now back to normal levels. Will keep an eye on this and re-open if issue returns, hopefully with more details as to which change triggers the CPU increase.

**Comment by foss-** [comment] 2021-12-01 21:12
Well that was a quick one. Connecting an external monitor makes CPU go up to ~55% playing a track and ~40-50 when ideling.
For comparison: when playing a track in Apples Music app CPU is around or mostly below 2%.

**Comment by jonaski** [comment] 2021-12-01 21:28
It might be related to #542

**Comment by foss-** [comment] 2021-12-01 21:32
Which gladly is seeing active development and just yesterday received patch set 8. Not sure if it is indeed the cause for the constant high CPU though, as no scrolling is involved in my tests.

**Comment by e471wo** [comment] 2021-12-06 07:51
duno if that help, but on my mac, if I put no analyser -> cpu down.

![image](https://user-images.githubusercontent.com/64007061/144807869-55b0277d-6b9f-49e8-b028-40ed6b75d5b0.png)

**Comment by foss-** [comment] 2022-01-17 10:48
Also confirming: Strawberry 1.0.1-22-g56b2630a on macOS 11.6.2 sitting idle ~40% CPU
Switching from `Block analyzer` to `No analyzer` and it goes to 0,0 sitting idle.

**Comment by jonaski** [comment] 2022-01-17 16:30
What about the other analyzers, do they cause as much CPU too?

**Comment by foss-** [comment] 2022-01-17 18:21
Strawberry idle / playing ~40% / ~60% for all analyzers.

**Comment by jonaski** [comment] 2022-04-01 16:26
The problematic code is in https://raw.githubusercontent.com/strawberrymusicplayer/strawberry/master/src/analyzer/analyzerbase.cpp
There is a timer that repaints every few milliseconds depending the framerate set.

**Comment by jonaski** [comment] 2022-04-15 20:45
Can you try the latest from https://builds.strawberrymusicplayer.org/macos/ those have Qt 6.3.0 (instead of Qt 6.2.x).

**Comment by foss-** [comment] 2022-04-15 22:42
macOS 12.3.1
Strawberry 1.0.4-5-g907dfee6
Scrolling up down like crazy still results in CPU ~100%.

**Comment by Calinou** [comment] 2022-05-15 17:45
It might be worth disabling the analyzer by default on macOS to fix the issue out of the box. I'm not sure how many people actually look at the analyzer anyway.

**Comment by jonaski** [comment] 2022-11-23 19:12
In my macOS Big Sur VM which is slow in general strawberry is using approximately 4% - 10% when idle and 15-30% when playing, both with the analyzer is on. If I turn the analyzer off when idle, the CPU goes almost to 0, when playing it's under 20%.
When removing timer that does frequent repaints when the analyzer is on, the CPU usage goes down, I also made a small test program, same thing happens with the test program, so it's not specific to the analyzer itself, but frequent repaints.
I'm considering filing a bug report to Qt, but at least for me, I also see the Activity monitor having somewhat high CPU usage, so my VM is not really ideal for benchmarking since it's so much slower than a real mac would be.
I don't think I can do much with this, so closing it for now. Turning off the analyzer as a solution for those having the issue is written in the Wiki: https://wiki.strawberrymusicplayer.org/wiki/Known_Issues

**Closed by jonaski** 2022-11-23 19:12 UTC
Labels: bug, help wanted
