### ISSUE TITLE
(Windows) Playback skipping first few bars/beats

### ISSUE THREAD

**Issue by vpmv** [strawberrymusicplayer/strawberry#495] opened 2020-07-30 11:22 UTC
**Describe the bug**
Playback will often skip the first bar of a song, resulting in weird transitions and beat placements and overall annoyance since the song isn't played back properly. Many songs contain an essential intro, which get muddied due to this bug.
I've played with the buffer and output settings, but it's unaffected. 

The skip only occurs in the first 2 seconds of playback, not in all songs but the ones that are affected keep showing the issue each time. 

My music is "streamed" from a NAS, most of them in FLAC (either ripped or direct download). The library info (xml files) is maintained on the local ssd.<br>
Playback is normal in other players (PLEX, WMP, Clementine) but they lack other features I require.

**To Reproduce**
Play any song with a "strong" intro

**Expected behavior**
Playback without skipping a beat

**Screenshots:**
N/A

**System Information:**
 - Operating system: W10 Pro
 - Strawberry Version: 0.6.12
 - Hardware: Ryzen 7, 32G ram etc. (3 months old)

**Additional context**
TBA

**Comment by jonaski** [comment] 2020-07-30 12:39
I have never seen this problem, and I can't reproduce it.
Does it work locally? What DAC or soundcard do you have? How do you stream from the NAS? ie.: Is it HTTPS or SMB? If SMB, how is mounted?
Does it work with gst-launch-1.0?
Install https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-mingw-x86_64-1.16.2.msi
Then run:
`gst-launch-1.0 souphttpsrc location=url ! decodebin ! audioconvert ! audioresample ! directsoundsink`
from c:\gstreamer\1.0\x86_64\bin
(Replace url with a URL you stream from).

**Comment by vpmv** [comment] 2020-07-30 14:46
The problem persists even when I play the file locally. The file system is mounted via default Windows network drive mapping (so I guess samba).

I'm outputting through a Focusrite Scarlett 2i4. I use this system for my DAW as well and this is the first time I'm experiencing this problem.
Bit hesitant to install gsteamer as I'm not sure if this will conflict with other drivers.

**Comment by jonaski** [comment] 2020-07-30 14:52
Can you send me a problematic file on email?

**Comment by vpmv** [comment] 2020-07-30 15:10
I'm transferring some FLAC files, as the problem seems to stick to that file type only. I'd have to test AAC and MP3 more to make definite conclusions. It's also persistent on entire albums, so there's something there.

**Comment by jonaski** [comment] 2020-07-30 19:24
The two files you sent plays fine here, both on Linux and on Windows. I play them on Windows through samba share from the Linux machine. I have also tested playing them from a QNAP that is located in a different place in the house and does not have SSD drives. Works fine.
Do you have any specific settings configured in Strawberry? Do you have antivirus installed or another program that could "scan" files at the same time you press play?

**Comment by jonaski** [comment] 2020-08-02 12:45
Closing this as I can't reproduce even with the same files. It's most likely a system related issue.

**Comment by jonaski** [comment] 2020-10-04 15:08
Similar problems reported here: https://forum.strawberrymusicplayer.org/topic/75/i-get-stutter-jump-when-starting-flac-files/9

**Comment by jonaski** [comment] 2020-10-04 15:10
Can you try the latest build from here https://builds.strawberrymusicplayer.org/windows/, (currently StrawberrySetup-0.7.2.211.g22bfbab8-x64.exe). Select "Stream audio to WASAPI" in backend / output.

**Comment by jonaski** [comment] 2020-11-29 08:05
Please try the newest build on https://builds.strawberrymusicplayer.org/windows/
I've compiled gstreamer using the latest git code. WIll reopen if this is still a problem.

**Closed by jonaski** 2020-11-29 08:05 UTC
Labels: help wanted, need more info
