### ISSUE TITLE
Segmentation fault when moving playlist items

### ISSUE THREAD

**Issue by TheBlackKoala** [strawberrymusicplayer/strawberry#1261] opened 2023-08-23 09:41 UTC
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Moving items in the gui causes segmentation fault - i have tried using --verbose but i still only see the segmentation fault message

**To Reproduce**
Move a song from collection, between playlists or within a single playlist

**Expected behavior**
The item should be moved to the correct place in the playlist

**System Information:**
 - Operating system: Manjaro Arch Linux (updated to verify it was not the system causing trouble)
 - Strawberry Version: Strawberry 1.0.18-102-g57e29b2b

**Comment by nokia8801** [comment] 2023-08-27 20:28
#1245 and #1257. Fixed with qt6-wayland 6.5.2-2 on Arch Linux. Wait for it to release on Manjaro.

**Comment by jonaski** [comment] 2023-08-28 20:15
This is probably duplicate of #1257, a Qt wayland bug. If not please provide a backtrace and I'll reopen.

**Closed by jonaski** 2023-08-28 20:15 UTC
