### ISSUE TITLE
Albums combined even if different Album Artist

### ISSUE THREAD

**Issue by dbolton** [strawberrymusicplayer/strawberry#1276] opened 2023-09-24 05:20 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
A two-part bug: 

First, Strawberry combines albums with the same Album Title, even if they have different Album Artists. 

Second, after I edit the Album titles to work around this, Strawberry Player didn't automatically update. 

**To Reproduce**
I have a three CD set called "Celebrating The Best of Jazz". The Louis Armstrong CD shows as it's own album (presumably because of the uppercase "Of"). The Duke Ellington and Count Basie CDs show as one combined album.
![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/19be244d-7a73-4209-a616-5f62494f027c)

In an attempt to separate all three I relabeled the Album Title (using foobar2000 music player, since it let me see and edit the individual albums)
- Celebrating the Best of Jazz (Armstrong)
- Celebrating the Best of Jazz (Basie)
- Celebrating the Best of Jazz (Ellington)

**Expected**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/c6cf8313-e717-4b20-9123-c64586a779c0)
First, I would expect the three albums to show separately before the renaming (since they had different Album Artists). In broad case of separate Artists releasing albums with the same title, Strawberry shouldn't combine them if the Album Artist is different.

Second, I would expect to automatically see the new Album Titles in Strawberry player after editing them. 

**Actual**
I didn't see the Album Title automatically change in Strawberry (even after closing and reopening the Player multiple times). 

My settings are checked for "Update the collection when Strawberry starts" and "Monitor the collection for changes."

**Workaround**
First, I relabeled the Album Titles so they were distinct. 

Second, to fix the metadata, I selected Tools > Do a full collection rescan

**System Information:**
 - Operating system: Windows 10 
 - Strawberry Version: 1.0.18-71-g560712db

**Comment by jonaski** [comment] 2023-09-24 11:08
What is collection group by set to?

**Comment by dbolton** [comment] 2023-09-24 21:18
Applies to the following
- Group by Album
- Group by Genre/Album

For comparison, here's the Album views in other media players:

Windows Media Player
![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/6813f788-f39c-4709-8317-a99718fdd395)

Jellyfin
![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/20234e3e-11e7-45b2-a1ad-6479240a041c)

foobar2000
![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/6e36f487-227c-455f-b73c-957e4a8d255f)


For reference, here's meta data for each Album. (Note Strawberry is one of the few that correctly pulls the front cover art instead of the back cover art). 
![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/d94f8729-30f6-4cb6-87e9-4e66528c0136)

![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/73855097-4a43-4615-a55a-bd25e7d191b4)

![image](https://github.com/strawberrymusicplayer/strawberry/assets/712270/ea1a5b8d-b5a4-43fb-84df-327a23340f0c)

**Comment by TheJanzap** [comment] 2023-09-26 17:01
I have a similar bug: When I select "Group by Album Artist/Year - Album" all albums that share the same name but with different album artists are listed under "Various artists".

Example: Both Blur and Die Ärzte have released albums titled "13". They are both listed under "Various Artists", even though their Album Artist tag is set to Blur and Die Ärzte respectively.
![image](https://github.com/strawberrymusicplayer/strawberry/assets/16736682/0719423c-79b5-4cd1-bac6-ee27f058c273)

**Comment by dbolton** [comment] 2023-09-27 02:37
@TheJanzap I'm not able to reproduce what your describing. Do you have "Album artist" specified as "Blur" and "Die Ärzte" for every track on the respective albums (and not just the "Artist")?

**Comment by TheJanzap** [comment] 2023-09-29 16:49
@dbolton Yes, all tracks on both albums have both the "Album Artist" and "Artist" tags set to their respective artist. All tags are distinct, except the album title.
![image](https://github.com/strawberrymusicplayer/strawberry/assets/16736682/b3f86cad-6f46-4006-918d-6297706fedd3)

**Comment by jonaski** [comment] 2023-10-06 22:22
@TheJanzap That's not a bug, but expected behavior. If there are albums with the same a album name, but different artists in the same directory, automatic compilation detection kicks in and it's grouped under various artists. I'm not sure why you have different album artists for the same album, usually the album artist for the album should be the same, but artist different. You can override the compilation detected by right clicking on the album and select "Don't show in various artists".

**Comment by TheJanzap** [comment] 2023-10-12 17:36
@jonaski 
> If there are albums with the same album name, but different artists in the same directory, automatic compilation detection kicks in and it's grouped under various artists.

I understand why it's done this way, but the way my tags are configured this really isn't needed. I only want albums showing up under Various Artists if the album artist is set to Various Artists. Is there a way to disable auto compilation detection globally without having to mark every album with "Don't show in various artists"?

> I'm not sure why you have different album artists for the same album, usually the album artist for the album should be the same, but artist different. 

My tags are exactly how you describe them: The album artist is the same across an album with sometimes differing artist tags for featured artists.

**Comment by jonaski** [comment] 2024-04-02 15:05
This isn't fixable with the current model, and album only groupings aren't currently loading well without lagging the entire GUI anyway, I will try to address this instead as part of a major rewrite in #729.

**Comment by jonaski** [comment] 2024-06-24 17:22
This is fixed now, if you group by album at the first level, it will separate albums if they have different artist, I've also added an option to turn off "Various artists".

**Closed** 2024-06-24 17:21 UTC
Labels: bug, confirmed

**Comment by sonic2kk** [comment] 2024-07-21 02:07
Is there a way to restore the previous behaviour? That is to actually group album artists? I absolutely see the value in separating them, but wondering if there is a way to go back. I have been fiddling with the Advanced Grouping options for a while and can't find a way to restore the old behaviour.
