### ISSUE TITLE
Songs from FLAC+CUE sheet keep playing after reaching end

### ISSUE THREAD

**Issue by OlegAckbar** [strawberrymusicplayer/strawberry#1568] opened 2024-09-27 18:57 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When playing songs from CUE+FLAC they continue to play file after the end of the song.

**To Reproduce**

1. Open a single song from CUE sheet of FLAC file
2. Reach to the end of the song

**Expected behavior**
Playback of a FLAC file will continue

**Screenshots:**
![изображение](https://github.com/user-attachments/assets/8366484b-ee8a-40f7-932b-f3348e8de547)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.1.3
 - GStreamer Version: 1.24.8

**Comment by jonaski** [comment] 2024-09-29 01:35
I can't reproduce this, is this with ALSA, Pipewire or PulseAudio? With or without automatic cross-fading enabled?

**Comment by OlegAckbar** [comment] 2024-09-29 08:59
@jonaski I use "Wrapper audio sink for automatically detected audio sink" (don't know what it is using underneath) while my sound server is Pipewire. This issue only occurs with automatic cross-fading **disabled**. With automatic cross-fading enabled issue doesn't occur.

**Comment by jonaski** [comment] 2024-09-29 09:58
Please try setting output to "Plays audio to a PulseAudio server", make sure you have pipewire-pulse installed.

**Comment by OlegAckbar** [comment] 2024-09-29 10:02
@jonaski still happening

**Comment by OlegAckbar** [comment] 2024-09-29 10:23
I've managed to reproduce this issue on a clear Arch VM by adding a single song from CUE sheet and setting both **Repeat playlist** and **Shuffle all**

**Comment by jonaski** [comment] 2024-09-29 10:58
I'm not sure what's causing it, I did some huge changes to the engine code in 1.1.2 mainly to fix some UI blocking issues with Spotify, that might have caused it, but I can' reproduce it.
I only have a couple of albums with CUE that users sent me for testing, I will try to rip some CD's to CUE FLAC, are there any rippers that does it for Linux?

**Comment by OlegAckbar** [comment] 2024-09-29 11:09
I think K3b can do this.

**Comment by jonaski** [comment] 2024-09-29 19:08
I can reproduce it when the next song in the playlist is not the next song in the file.

**Comment by KazimirPodolski** [comment] 2024-10-17 15:24
@jonaski could you please release a new version with this fix?

**Comment by jonaski** [comment] 2024-10-17 20:12
That was the plan, but I got sick

**Comment by KazimirPodolski** [comment] 2024-10-17 20:18
@jonaski get better!

**Comment by jbhanks** [comment] 2024-11-20 06:59
I am having this issue on EndeavouOS/KDE/Pipewire.  What is more annoying is that the name of the playing track doesn't change, so if I like what I am hearing, I don't know which song I am listening to as it still says the first one that played, but with the playbar at the end. The moodbar seems to be gone while this is happening.

**Comment by jonaski** [comment] 2024-11-20 09:18
@jbhanks Which version are you using? This is fixed in 1.2.1-rc1, I plan to make a stable release today.
Moodbar isn't supported with CUE.

**Comment by jbhanks** [comment] 2024-11-24 15:02
1.2.0-0-ge6607fef

**Comment by jbhanks** [comment] 2024-11-24 15:03
> @jbhanks Which version are you using? This is fixed in 1.2.1-rc1, I plan to make a stable release today. Moodbar isn't supported with CUE.

 1.2.0-0-ge6607fef

**Comment by OlegAckbar** [comment] 2024-12-01 19:08
I don't know if this is related, but I'm still encountering this or similar issue. Sometimes, if the next song is playlist is from CUE sheet it starts to playing the entire file from start instead from song's offset while playback time is staying at 0:00.
![изображение](https://github.com/user-attachments/assets/55b4d443-bd14-4c3f-b511-5b128c80a4bd)

**Comment by jonaski** [comment] 2024-12-02 08:17
Do you have that problem with 1.2.1 / 1.2.2, or an older release?

**Comment by OlegAckbar** [comment] 2024-12-02 18:06
1.2.2

**Comment by jbhanks** [comment] 2024-12-03 18:34
So I updated to Strawberry 1.2.2 and am still having this issue. At the moment having it with a .ape file.

**Comment by jonaski** [comment] 2024-12-06 22:47
I don't know how I missed it, but there is a seek missing when switching song it play from the beginning of the file when already playing.
d66126f998dd85394e8148f08cb51cfaa8d9a634 should hopefully fix this now, if possible please try the latest code from master, I'd like a confirmation from someone else before releasing a new version.

**Comment by nicoadamo** [comment] 2024-12-07 14:45
Hi Jonas!
This is probably related:
The [whatsnew / announcement for version 1.2.1](https://forum.strawberrymusicplayer.org/topic/4871/version-1-2-1-released) said "Fixed playback of CUE continuing to play from the same file after the song has finished playing (#1568)."
I've seen it works fine when using the "next" button or function, but not when using the shuffle function. If shuffle is active and somehow a .flac file that has a .cue table is selected, after that song is finished, instead of jumping around to another song, the next one (part of the .flac & .cue) continues until finishing the whole album.
I don't know yet how to test [what you requested](https://github.com/strawberrymusicplayer/strawberry/commit/d66126f998dd85394e8148f08cb51cfaa8d9a634), but as soon as I find out, I will.

**Comment by jonaski** [comment] 2024-12-08 15:25
I've done a lot of testing with CUE songs and it seem to be working fine now. As I don't know if anyone is available to test, I've just released a new version now, 1.2.3.

**Closed by jonaski** 2024-12-08 15:25 UTC
Labels: bug, confirmed

**Comment by nicoadamo** [comment] 2024-12-08 18:49
Great news! Thanks a lot Jonas!
