### ISSUE TITLE
Audio glitch after stopping playback if "Fade out when stopping a track" is enabled

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1383] opened 2024-02-21 16:12 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
"Fade out when stopping a track" feature is not working. I hear an audio glitch after stopping a track instead of the expected fade out effect.

**To Reproduce**
1. enable "Fade out when stopping a track" feature in Backend section of Strawberry settings
2. play a track for a few seconds
3. stop the playback

**Expected behavior**
fade out effect after stopping playback

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment] 2024-02-25 02:13
This is could be a duplicate of https://github.com/strawberrymusicplayer/strawberry/issues/1376
Because Strawberry uses a volume to fade the out the track when stopping, when it hits zero it will glitch.
The bug is in GStreamer, and versions 1.22.9 and 1.22.10 are affected.

**Comment by jonaski** [comment] 2024-03-18 16:47
The change that caused #1376 has been reverted in GStreamer. I've also asked Arch linux if they can apply the patch: https://gitlab.archlinux.org/archlinux/packaging/packages/gst-plugins-base/-/issues/1
Need to test this again when that patch is applied.

**Comment by jonaski** [comment] 2024-03-19 22:30
gst-plugins-base was patched yesterday: https://gitlab.archlinux.org/archlinux/packaging/packages/gstreamer/-/commit/6d01eed5c5219320cfef123550abad64fb2b2942
Please check once the update is available if the issue is gone.

**Comment by glaubersm** [comment] 2024-03-21 23:31
I have just updated to gst-plugins-base 1.24.0-3, and now the bug is fixed.

**Closed** 2024-03-21 23:55 UTC
Labels: bug, upstream
