### ISSUE TITLE
Fedora 32 build error 

### ISSUE THREAD

**Issue by tla2k12** [strawberrymusicplayer/strawberry#459] opened 2020-06-16 10:30 UTC
**Describe the bug**
make fails with link error on the built-in tag library:

[ 48%] Generating /home/x/SRC/strawberry/src/translations/translations.pot
Scanning dependencies of target strawberry_lib
[ 48%] Linking CXX executable ../../strawberry-tagreader
/usr/bin/ld: ../../3rdparty/taglib/libtag.a(tstring.cpp.o): undefined reference to symbol '_ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEpLEPKw@@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [ext/strawberry-tagreader/CMakeFiles/strawberry-tagreader.dir/build.make:149: strawberry-tagreader] Error 1
make[1]: *** [CMakeFiles/Makefile2:567: ext/strawberry-tagreader/CMakeFiles/strawberry-tagreader.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Building CXX object src/CMakeFiles/strawberry_lib.dir/core/application.cpp.o

**To Reproduce**
$ cd strawberry-build
$ make clean
...
$ cmake ../strawberry
-- Strawberry Version:
-- Display:  0.6.12
-- Package:  0.6.12
-- RPM:      0.6.12-1
-- PAC:      0.6.12-1
-- Checking for module 'libxine'
--   Package 'libxine', required by 'virtual:world', not found
-- Checking for module 'libvlc'
--   Package 'libvlc', required by 'virtual:world', not found
-- Checking for module 'libgpod-1.0>=0.7.92'
--   Package 'libgpod-1.0', required by 'virtual:world', not found
-- Checking for module 'libimobiledevice-1.0'
--   Package 'libimobiledevice-1.0', required by 'virtual:world', not found
-- Checking for module 'libusbmuxd'
--   Package 'libusbmuxd', required by 'virtual:world', not found
-- Checking for module 'libplist'
--   Package 'libplist', required by 'virtual:world', not found
-- Checking for module 'taglib'
--   Package 'taglib', required by 'virtual:world', not found
-- Using builtin taglib library
-- Checking for module 'singleapplication'
--   Package 'singleapplication', required by 'virtual:world', not found
-- Checking for module 'libsingleapplication'
--   Package 'libsingleapplication', required by 'virtual:world', not found
-- Checking for module 'singlecoreapplication'
--   Package 'singlecoreapplication', required by 'virtual:world', not found
-- Checking for module 'libsinglecoreapplication'
--   Package 'libsinglecoreapplication', required by 'virtual:world', not found
-- Using builtin SingleApplication and SingleCoreApplication libraries
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 

Building strawberry version: 0.6.12

The following components will be built:
   ALSA integration
   Chromaprint (Tag fetching from Musicbrainz)
   D-Bus support
   Devices: Audio CD support
   Devices: GIO device backend
   Devices: MTP support
   Devices: UDisks2 backend
   Engine: GStreamer backend
   Global shortcuts
   Moodbar
   Pulse audio integration
   Subsonic support
   Tidal support
   Translations

The following components WILL NOT be built:
   Devices: iPhone, iPod Touch, iPad and Apple TV support (missing libimobiledevice, libplist, libusbmuxd, libgpod)
   Devices: iPod classic support (missing libgpod)
   Engine: VLC backend (missing libvlc)
   Engine: Xine backend (missing libxine)
   Sparkle integration (missing macOS, Sparkle)

CMake Warning at CMakeLists.txt:446 (message):
  sqlite3 must be enabled with FTS5.  See: https://www.sqlite.org/fts5.html

-- Configuring done
-- Generating done
-- Build files have been written to: /home/x/SRC/strawberry-build

$ make -j8
...
(see error above)

**Expected behavior**
make should complete without error

**Screenshots:**
N/A

**System Information:**
 - Operating system: Fedora 32 Workstation
 - Strawberry Version: 0.6.12 and today's master
gcc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)

This worked for Fedora 31:
sudo dnf --assumeyes install \
        boost-devel.x86_64 \
        gnutls-devel.x86_64 \
        protobuf-devel.x86_64 \
        alsa-lib-devel.x86_64 \
	dbus-c++-devel.x86_64 \
        glib2-devel.x86_64 \
        libxcb-devel.x86_64 \
	gstreamer1-devel.x86_64 libnice-gstreamer1.x86_64 gstreamer1-plugins-base-devel.x86_64 gstreamer1-plugins-good.x86_64 gstreamer1-plugins-bad-devel.x86_64 gstreamer1-plugins-ugly.x86_64 \
        libX11-devel.x86_64 \
        libcdio-devel.x86_64 \
        libXinerama-devel.x86_64 \
	libsqlite3x-devel.x86_64 \
        qt5-devel.noarch \
        fftw-devel.x86_64 \
        libchromaprint-devel.x86_64 \
	libmtp-devel.x86_64
cd ~/SRC && git clone https://github.com/jonaski/strawberry && cd strawberry && git pull && cd .. && [ ! -d strawberry-build ] && mkdir strawberry-build && cd strawberry-build && cmake ../strawberry && make -j8 && sudo make install

**Additional context**
I don't think I need any additional libraries as the build process selects the internal tag library?

**Comment by jonaski** [comment] 2020-06-16 15:48
I get the same error on my machine when using clang.
I can't tell from the output what compiler is used in your case. 
You should delete CMakeCache.txt or the whole build directory and rerun cmake so that the compiler detection is shown in the output.
It compiles fine on Fedora 32 in the CI here:
https://github.com/strawberrymusicplayer/strawberry/runs/774213489

**Comment by jonaski** [comment] 2020-06-16 16:43
The sqlite FTS5 test is failing too, indicating that there is linking issue already there.
Try: `LDFLAGS="-lstdc++ -lm" cmake ../strawberry`
See if the FTS5 test succeeds before you continue with make.
Closing this as it's not a bug but a problem with your compiler.

**Closed by jonaski** 2020-06-16 16:43 UTC

**Comment by tla2k12** [comment] 2020-06-16 21:51
Compiler was gcc (see under system information).  The previous time I built it was under Fedora 31. Good call, removing CMakeCache.txt and re-running cmake and make fixed both the strawberry-tagreader and the sqlite issue. Perhaps it would be a good idea to have the Makefile remove CMakeCache.txt under the clean target to prevent anyone else having the issue? Thanks! :)
