### ISSUE TITLE
Support for playing DSD audio files

### ISSUE THREAD

**Issue by bertusw** [strawberrymusicplayer/strawberry#633] opened 2021-01-16 15:33 UTC
would be nice if strawberry can play DSD audio files, so that i can play all audio files with my favoured player
the player i now use for DSD audio is https://deadbeef.sourceforge.io/ maybe an option to implement it.

**Comment by jonaski** [comment] 2021-01-17 00:05
Duplicate of #9

**Closed by jonaski** 2021-01-17 00:05 UTC
