### ISSUE TITLE
Song ratings

### ISSUE THREAD

**Issue by kjetilk** [strawberrymusicplayer/strawberry#259] opened 2019-08-31 23:03 UTC
**Is your feature request related to a problem? Please describe.**

To allow me to prefer certain songs in my playlists, to e.g. have a list of "the best" songs and "the good" songs, some way to express such a preference on a per-song basis is needed.

**Describe the solution you'd like**

It would be great to have song ratings. I started assigning ratings to songs in the Amarok 1.4 days, and it took a lot of work to set them. 

**Describe alternatives you've considered**

A possibility it to generate playlists based on my old Amarok 2 database using SQL, but that would be a lot of work.

**Additional context**

It also seems to be important for #132 to be efficient, and it is also mentioned in the example queries there.

**Comment by morfikov** [comment] 2019-09-04 13:20
I also missing the ratings, which were a nice thing in amarok.

**Comment by jonaski** [comment] 2019-09-04 15:31
Ratings are easily lost if songs are moved on disk, files renamed, or simply changing permissions.
Yes it's possible to save it to tags, but not everyone want that, and in any case it should be optional and off by default.
I believe song fingerprinting with chromaprinter can solve it, so implementing that first is a good idea, it's unique both when filenames and tags are changed.

**Comment by kjetilk** [comment] 2019-09-04 20:39
To attach it to a fingerprint would certainly be nice, and yes, they can easily be lost. I have written more than one script to take it from one database to another in my days, but I find the usefulness of having them (and having expended a lot of effort), that I'm willing to put up with that. So, just putting them in the database for now would be fine with me.

**Comment by desputinski** [comment] 2019-09-09 14:45
Hi, I agree that song ratings are important. I have been using it with clementine since the beginning of clementine and before with amarok 1.4. The ratings are stored in a mysql-database, which can be edited e.g. by the sqlitebrowser in Linux easily. I'm using that database on several different machines. Paths on different computers are a problem but I've been solving it by creating symlinks on all of my computers, linking to /media/Daten2/musik...

**Comment by SaiyanRiku** [comment] 2019-09-15 08:12
It was possible with Clementine to save ratings in file tags. For me, this features is very important because i synchronize my musics between three computers, and i don't want to rate manually on each machines.

**Comment by desputinski** [comment] 2019-09-16 13:22
> It was possible with Clementine to save ratings in file tags. For me, this features is very important because i synchronize my musics between three computers, and i don't want to rate manually on each machines.

Hi @SaiyanRiku : How do I set clementine, so it stores ratings in the sound files?

**Comment by SaiyanRiku** [comment] 2019-09-16 13:30
You have to enable the option "Save rating in file tag when possible" in the "Music library" preferences. Look here : https://lh3.googleusercontent.com/-S_16c7UC3Aw/WIfMAr5k0nI/AAAAAAAABqc/mjv6in4KPHcogVmt4Ii4DU8s90UKkxiGQCHM/s827/lib.png

**Comment by jonaski** [comment] 2019-10-04 16:16
I will try to add song ratings and smart/dynamic playlists back since it's the two most missed features that Clementine and Amarok had. I almost finished smart playlists, but I ran into some issues with a crash and ran out of time finishing it, then I started fixing other things in the playlists so it has to be merged with the up to date sources in master.
Before adding ratings back, I want to add song fingerprinting, or at least give it a try and see how it works, otherwise there will be lot's of complaints about losing ratings.

**Comment by desputinski** [comment] 2020-02-07 18:47
Hi, I was wondering if there is anything new on this subject

**Comment by eggsperde** [comment] 2020-02-09 19:10
I found out about Strawberry today and it made me really happy. Thanks a lot for your efforts!

I currently use Clementine and there is not much wrong with it, except that there are no new versions. My favorite part of it are the song ratings and I would much appreciate if they could become part of Strawberry, too. Writing it to tags, e.g. the comment would be fully sufficient for my needs but any option is fine. 

Have a good one!

**Comment by biffster** [comment] 2020-08-17 15:19
Hello, @jonaski ! Thank you for the time you've spent with Strawberry, the project is moving along very nicely. Song Ratings are my #1 most needed feature in a music player, it's why I loved Amaraok 1.4, why I used Clementine up until recently, and it's why I won't be using Strawberry much. I wish my coding chops were up for being able to help implement this feature, but alas, it is not. I'll keep an eye out on Strawberry and will give it another try if you are able to get Ratings working though.

**Comment by jonaski** [comment] 2020-08-25 18:04
I'll post this here as a general update to the Strawberry project as a whole since there is a lot of feedback from different users on this issue. (I still intend to add ratings and smart playlists back, read until the end).

Thanks for all the positive feedback so far, and to the ones that have been donating money through PayPal.

I have been ill for the past 3 months or so. I had some back pain that didn't go away, and have been in a lot of pain. Basically my back collapsed in May. I had a hard time even standing up. It's a bit better now, but I still can't do much physical work without getting the pain back. I have been sick on and off from my day job for weeks.
I have something called "modic 1 changes" which is something the doctors know very little about: https://en.wikipedia.org/wiki/Modic_changes

Anyway, as you have probably have seen, the development on Strawberry has not stopped because of this, it is, and have been in almost continuous development for the past 3-4 years. I make frequent releases almost every month. I have been concentrating on bugfixes and improvements to the existing codebase, which will always be my main priority. Bugs that can be reproduced and solved are fixed almost the same day they are reported. @glaubersm have reported lot's of bugs that have been helpful too, so I've fixed many bugs I did not immediately see myself.

These are some of the things that have been done in the past months (some of the biggest changes):

1. All the code has been renewed, and everything is now 100% compatible with Qt version 6. Which puts the whole project in a good position for the future since we now are both compatible with Qt 5 and 6. We probably need to do little, or no changes to make it work with the final release of Qt 6 in November.

2. We use our own copy of TagLib, where almost all changes from TagLib 2 are adapted, my own changes to TagLib has been manually merged with the official TagLib 2 branch, which was a huge job since I made my own changes to TabLib I could not just copy TagLib 2 over. I found that I had already done so many of the same changes that were in TagLib 2 that we might as well adapt the rest of it. (The TagLib project is currently without a maintainer, and have stalled, we more or less needs to maintain it ourself). This is probably the only library we use that is no longer in development upstream, so we need to continue to include our own copy. I have considered switching to a different library called tagparser: https://github.com/Martchus/tagparser that is in continuous development, but I think that would mean even more work.

3. A lot of the UI has been improved to use less fixed fonts and icons, this is so it works better with higher resolution and scaling. Some icon sizes can also be configured. This is probably where Strawberry could still be improved, because our UI is based on a 10 year old design. We will probably not want to change too much of the UI, because it is what users are familiar with, and for many users, the current design is why they use Strawberry or Clementine.

4. Strawberry probably has the best cover and lyric providers of any music player on Linux (Tidal has 1500x1500 and Deezer has 1000x1000 resolution covers), these have been improved even more. They have been improved so that matches are very accurate. For album covers for streaming where we can search some of the API's by artist and song title to get album results. They also have a score system so that the best result is always picked. For lyrics, many more providers have been added, we only had 1 before. We now have 6 lyric providers, with some of the biggest lyrics databases available such as Genius and Musixmatch. All of them are using API's except for Musixmatch. All are configurable in the settings. We can also easily add new providers that require OAuth based login.

5. Streaming support have been improved to work with covers, lyrics and scrobbling, the "add stream" option is also added to the menu. Strawberry now works much better with internet radios.

6. Most of the issues on macOS have been fixed, which means we can continue to make releases for macOS. There have been a ton of problems related to macOS so this has been a huge job, even when most issues have been minor, it has been a lot of work to get it to this point. This is one of the things I have spent a ridiculous about of time on, mainly because I have not been familiar with macOS API's, objective C and python (and I don't have a mac, I'm am 100" linux only user). (and I have no personal interest in running it on macOS myself).

7. Automatic updating when there is a new version is functioning for macOS and Windows.

8. The analyzer problems has finally been fixed to work with all bit depths formats without affecting bit depth of the output.

9. Many other bug fixes and improvements which most of it can be seen in the changelogs.

10. Tidal works with OAuth, which is pretty cool, this means we can continue development on the Tidal support, and hopefully keep the Tidal support in the future too.

When things settle a bit in regard to bugfixing, I will probably look into completing ratings and smart playlists again since it's 2 of the most missed features from Amarok and Clementine. They require database schema updates which means we need to be extra careful as it can potentially more easily break something.
I wanted to make some changes to those features before I bring them back. The smart playlists code is large.
I have no interest in those features myself, but as Clementine is more or less abandoned I think it's necessary to have those 2 back since a lot of users want them. Once that's finished we can look into other features again, but right now the features in the current open issues are the only thing I have capacity to do. It is still possible to suggest and discuss new features on the forum, but having open issues on GitHub for features we don't have capacity to do anyway will just give false impression that something will be added. It is also impossible and unrealistic to do what everyone wants.

I hope everyone who uses Strawberry will consider becoming a GitHub sponsor on my profile. Even though some have been donating on Paypal, I am very thankful to those. There are still no sponsors which is a bit disappointing. Continuing donation through GitHub sponsors will help secure the project in the future, and it will encourage the continuing development of Strawberry, it also takes a lot of time to continue support for Strawberry through GitHub issues and on the Forum. It is possible to sponsor as low as 2 dollars per month which most could afford. So please consider it.

**Closed** 2020-09-17 15:51 UTC
Labels: enhancement

**Comment by breversa** [comment] 2020-09-26 13:32
Can we expect a release soon ? I'd love to try and give feedback. :-)

**Comment by morfikov** [comment] 2020-09-27 14:43
@jonaski 
I tested the ratings and I have couple of thoughts on it. So basically it looks like this:

![2020-09-27_16-37](https://user-images.githubusercontent.com/3797768/94367563-09592700-00cf-11eb-893d-1bff20e15dcf.png)

Not all songs have the rating displayed. Any ideas why?
The color of the stars could be yellow/orange, because with this gray one sometimes it's hard to see them,

**Comment by jonaski** [comment] 2020-09-28 13:12
Ratings are only available with collection songs

**Comment by morfikov** [comment] 2020-09-28 13:19
What's the difference, and how can I tell which one song can have ratings and which one can't?

**Comment by breversa** [comment] 2020-09-29 13:37
@morfikov :
The files that are "in your collection" are those located in your "Collection" folders (that you defined in the application’s settings).
Typically, it’s the files in `home/${USER}/Music`

Files that are outside those folder are "out of collection". You can still play them, but won’t be able to rate them, as song ratings are (apparently) stored in Strawberry’s database, and not in the files’ tags (contrary to _artist_, _title_, etc.).

That also means that if you move your files to another device, your ratings won’t be carried over.

Hope that cleared things out. :-)

PS :
Great music taste BTW ! I prefer "Heroes" myself, but Carolus Rex is awesome, and so is the concept of a dual english/swedish album. ;-)

**Comment by morfikov** [comment] 2020-09-29 13:43
But all of those files are in the collection folder.

This is the example file from the one above without stars:

`/media/Kabi/mp3/Daughtry/[2018] - Cage To Rattle/04. As You Are.mp3`

And this is the collection folder is: 

`/media/Kabi/mp3/`

So something else matters here.

**Comment by breversa** [comment] 2020-09-29 13:44
No : _nothing_ else matters. 😛 

Joke aside, that’s weird.
What’s the path of _Poltava_, for instance ?

**Comment by morfikov** [comment] 2020-09-29 13:46
It's

`/media/Kabi/mp3/Sabaton/(2012) - Carolus Rex/09 - Poltava.mp3`

**Comment by breversa** [comment] 2020-09-29 13:49
🤔 
Maybe Strawberry chokes on the "**[**2018**]**" (brackets) characters to determine if it’s in collection or not ?
What about write permission on the file ? It really shouldn’t matter, but it won’t hurt to check.

Otherwise, @jonaski, can you help us ?

**Comment by morfikov** [comment] 2020-09-29 13:52
No, I have mix of () and [] and others what have () or [] have stars. For instance:

`/media/Kabi/mp3/Daughtry/[2009] - Leave This Town/10 - Supernatural.mp3` 

And this one has stars.

**Comment by breversa** [comment] 2020-09-29 13:54
Then I’m sadly out of idea for the moment. :-( I hope @jonaski will be able to answer.

**Comment by morfikov** [comment] 2020-09-29 13:55
Yes, it's really weird.

**Comment by breversa** [comment] 2020-09-29 13:57
Have you tried doing a full re-analysis of your collection ? Or resetting it by moving all your files elsewhere (ou simply changing the collection folders) then back ?

**Comment by morfikov** [comment] 2020-09-29 14:04
I fixed it. Something is wrong with adding the stars after updating strawberry. I removed the files from the list, and readded them. Now the start are shown. So basically it's better to recreate the list anew after updating the app to the newer version.

**Comment by breversa** [comment] 2020-09-29 14:05
Awesome ! Thanks for finding the cause and sharing your solution, @morfikov ! :-)

**Comment by glaubersm** [comment] 2020-09-30 13:28
I'm trying to use this new feature with a nightly build of Strawberry but I can not even enable "Rating" column.
I right-click on any column, I check "Rating" column and it does not appear in the columns bar despite it is checked as expected
when I right-click on any column again. Then I restart Strawberry and "Rating" column is unchecked again in the context menu of the columns bar.

**Comment by jonaski** [comment] 2020-10-01 18:40
You can see if the songs are identified as collection songs by the "source" column in the playlist.
If some of the songs have not been identified as collection songs it could be because they are added before the directory were added to the collection, or they have been added from the file view, or by drag/drop and the path is different, i.e.: symbolic links.

@glaubersm That's strange, did you try to reset the columns in the right click menu?

**Comment by jonaski** [comment] 2020-10-01 19:31
@breversa There are major changes to the collection/groupings code, and now also the player --> playlist code that needs more testing before a final release. The collection changes (specifically the collection model code) were just simply to important to leave out and needs to be in the next release in any case.
It would be helpful if as many as possible could do testing.

**Comment by glaubersm** [comment] 2020-10-02 03:01
> @glaubersm That's strange, did you try to reset the columns in the right click menu?

Resetting the columns solved the problem. Thank you.

**Comment by breversa** [comment] 2020-10-03 13:50
@jonaski Testing 0.7.2-197-g61ffb7d9 right now (Linux Mint 20/Ubuntu 20.04). Thank you ! ;-)

**Comment by jonaski** [comment] 2020-10-03 14:12
I made a list of things to test here: https://forum.strawberrymusicplayer.org/topic/89/testers-needed-before-new-release

**Comment by RyuzakiKK** [comment] 2020-10-13 09:32
@jonaski From what I can see the rating is stored only in Stawberry's library and not in the song file tag `FMPS_RATING`, like Clementine, is that correct?
