### ISSUE TITLE
Strawberry will hang at 99% when updating my Subsonic catalog

### ISSUE THREAD

**Issue by CENTSOARER** [strawberrymusicplayer/strawberry#718] opened 2021-05-26 19:55 UTC
Strawberry seems to stop updating my Subsonic catalog at 99%. In the past, I was able to interrupt the process and use the previous database but, while trying to fix the issue, I wiped the database, and now I can't seem to build a new one.

Well, I've had this kind of problems in the past, it is usually a weird character that's impossible to decode. Some candidate files were deleted but the problem remains. I would like to have Strawberry to finish the scan or, at least, to tell me what file is causing the problem in my collection.

Strawberry detects the correct number of albums in the server and progresses steadily until 99%. If I inspect the strawberry.db file in my .local directory I can obtain the entries of all Strawberry devices. The local music folder in the database lists all entries I expect, but the Subsonic columns in the subsonic_songs table will throw a count of 0 items, so, the 99% of progress while scanning my Subsonic collection is not indicative of the database being fed with data. Running strawberry from the command line will not throw any relevant errors AFAICT, nothing relevant is shown after:
 ```
DEBUG Database:492                     Starting database integrity check
DEBUG Database:555                     Starting database backup
```
This occurs with Strawberry 0.9.3 in the official Arch Linux repo, but also with the other versions in the AUR.

**Additional context**
This is a Nextcloud installation with the Music app's subsonic server embedded. Sublime Music connects flawlessly. 0.8.x versions of Strawberry were working fine, but maybe a recent upload is causing this lately.

I prefer using Strawberry for so many reasons. Any ideas of what's going on with my setup will be appreciated. I'm also up to further debugging, but $strawberry --log-levels has been already explored.

EDIT: I still guess it should be a specific file. I partially updated the Subsonic server database to only load 3 albums and Strawberry can read this short catalog with no problems whatsoever. I still leave the issue opened, since the debugging part is still relevant for me.

EDIT 2: Went 1000 by 1000 songs updating the Subsonic server database. Already stuck, but most of the catalog is in Strawberry database. I am back at the 99% progress with no clue about what file might be causing the issue.

**Comment by jonaski** [comment] 2021-05-26 22:56
I'm not sure what progress you referrer to, there are 3 progresses for getting the data from subsonic, and one for updating the DB.

**Comment by CENTSOARER** [comment] 2021-05-27 18:00
It is the first one, I think, it displays the "Retrieving songs for 1093 albums..." message. The number of albums seems to be correct and if I delete albums in Subsonic, they get updated here.

**Comment by jonaski** [comment] 2021-05-28 21:29
The only thing I can see that would result in this behavior is if the server is stopping sending data.
If a song is invalid than it should finish without that song.
I don't think I will be able to figure out why unless I have access to a server where this problem can be reproduced.
If you want, you can send me a login on e-mail and I will look into it.

**Comment by CENTSOARER** [comment] 2021-05-29 19:28
I just sent you an email titled "About an open issue in Strawberry github (99% updated catalog in Subsonic)". I really hope you can spot the issue. If I could know if there is an order followed by Strawberry to feed the database, that would help me too, but I can't tell by the rowid if Strawberry follows any specific order to build the database...

**Comment by jonaski** [comment] 2021-05-29 21:33
I tested several times, both with the option to download covers and without. It works fine here.
Both options works, however it rejects the covers because it didn't understand the mimetype reported by the server.
Should be fixed in https://github.com/strawberrymusicplayer/strawberry/commit/e6f50e66370733514cab4ec7673758564752940a
Everything works without that fix, however it will request the cover each time you play a song.
So I have no idea why it doesn't work for you.

**Comment by CENTSOARER** [comment] 2021-05-29 21:40
Thanks for taking the time. I just can't figure it out. Clementine 1.4 rc2 does finish the scan here. In Strawberry, I can get until ~11300 files, after that nada. I guess is a local configuration. I will close the issue now. If you can think of something else I'll be around.

**Comment by CENTSOARER** [comment] 2021-06-12 20:29
@jonaski I built the strawberry-git package for the AUR in Arch Linux, same result. Most Qt apps I use are employing the Qt5 toolkit, so I built Strawberry with Qt5 instead of Qt6 to economize on installed packages (default in Arch Linux now, seemingly, or at least in the AUR package). 

So... long story short, Subsonic catalog update finishes with Strawberry-Qt5, but still halts at 99% with Strawberry-Qt6.

**Comment by jonaski** [comment] 2021-06-13 12:21
I didn't test with a Qt 6 release, I tested with the latest Qt 6 code from the dev branch, which is what will be become Qt 6.2.
So the problem might be with Qt 6.1.
If you open the login again I can test with Qt 6.1.
Between, I maintain Strawberry on openSUSE, it uses Qt 6 on Tumbleweed, but Qt 5 on Leap releases.

**Comment by CENTSOARER** [comment] 2021-06-13 16:52
You can access with this password: k8c48mypba9m. The other settings are the same as in my email.

I can confirm the Qt6 version in Arch Linux is 6.1.1, but I got rid of OpenSUSE Tumbleweed a couple of days ago. I will try again when Qt6.2 drops in the official repos. Meanwhile, I'll keep Strawberry-Qt5. Please, close the issue at your own discretion, I just thought it might be relevant to know what was causing the halt.

**Comment by jonaski** [comment] 2021-06-13 17:37
I can confirm the issue with Qt 6.1.1.
The bug is probably in Qt, the reason it only affects Qt 6 is that Qt 6 uses HTTP2 by default while Qt 5 does not.
I can confirm that it works fine when setting Http2AllowedAttribute to false, meaning it will force HTTP1.
It is probably already fixed since it works with the Qt Dev branch.
I can add an option to the setting to turn off HTTP2.

**Closed** 2021-06-13 17:56 UTC
Labels: bug, confirmed
