### ISSUE TITLE
Playback hangs in pause state if fade on pause/resume is enabled

### ISSUE THREAD

**Issue by adem4ik** [strawberrymusicplayer/strawberry#1060] opened 2022-10-28 11:37 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Playback hangs in pause state after clicking on play/pause a few times.

**To Reproduce**
1. Enable Settings > Backend > Fade out on pause / fade in on resume
2. Start playing any track
3. Click on play/pause button (or corresponding shorcut) a few times

**Expected behavior**
The same behavior of play/pause button if `Fade out on pause / fade in on resume` option is disabled.

**Screenshots:**
N/A

**System Information:**
 - Operating system: Manjaro KDE
 - Strawberry Version: 1.0.9

**Additional context**
```
inxi -A
Audio:
  Device-1: Intel 82801AA AC97 Audio driver: snd_intel8x0
  Sound API: ALSA v: k5.15.74-3-MANJARO running: yes
  Sound Server-1: PulseAudio v: 16.1 running: yes
```
Similar issue with the same condition is presented in Clemetine player: https://github.com/clementine-player/Clementine/issues/7227

**Comment by jonaski** [comment] 2022-11-09 22:12
I can't reproduce this, if you have pipewire or PulseAudio active, can you try disable them and set output to ALSA with pcm as ALSA plugin, it should allow you to still select the fading options.

**Comment by adem4ik** [comment] 2022-11-27 09:48
@jonaski Thanks for reply. Using ALSA as a output fixed my issue.
![image](https://user-images.githubusercontent.com/4707112/204128897-31ecd0d8-c5b4-416e-9f80-bfea8a366f68.png)

**Comment by jonaski** [comment] 2022-11-27 20:55
Closing this as it' not likely a Strawberry bug.

**Closed by jonaski** 2022-11-27 20:55 UTC
