### ISSUE TITLE
Strawberry doesn't maximize properly from tray

### ISSUE THREAD

**Issue by ShiroYasha139** [strawberrymusicplayer/strawberry#1182] opened 2023-04-16 17:04 UTC
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When clicking the icon from the taskbar to maximize the app, sometimes it doesn't maximize properly and does below the current window. 
For Example, if I have Firefox running and click the icon, it'll maximize but behind firefox so either I have to minimize Firefox to see Strawberry or click the icon again twice. 

**To Reproduce**
1) Start the app
2) Keep it in tray
3) Wait for a few minutes
4) Click the app icon from taskbar 

**Expected behavior**
App should maximize properly each time from taskbar. 

**Screenshots:**

**System Information:**
 - Operating system: Endeavour OS x64
 - Strawberry Version: I'm currently using strawberry-qt5 from the AUR, but this happens in the original app as well. 

**Additional context**

**Comment by jonaski** [comment] 2023-04-17 17:20
I have never seen this issue on Linux, works fine here on X11, both with XFCE and KDE.
Is this X11 or Wayland? What window manager? What desktop environment?

**Comment by ShiroYasha139** [comment] 2023-04-18 16:49
> I have never seen this issue on Linux, works fine here on X11, both with XFCE and KDE. Is this X11 or Wayland? What window manager? What desktop environment?

I'm on KDE with X11, the default i think thats Kwin?

**Comment by jonaski** [comment] 2023-04-20 15:19
I can't reproduce it here so I suggest that you check this with the Endeavour community if someone else there can reproduce it too, to figure out if it is specific to your configuration or Endeavour.

**Comment by jonaski** [comment] 2023-08-01 14:02
Closing this as I can't reproduce it.

**Closed by jonaski** 2023-08-01 14:02 UTC
