### ISSUE TITLE
Plasma media player applet problem

### ISSUE THREAD

**Issue by yavuzmert** [strawberrymusicplayer/strawberry#565] opened 2020-10-21 23:59 UTC
**Describe the bug**
Hi, there is a strange problem with Plasma media player applet integration. When strawberry if left as only media application, media player applet is hidden.

**To Reproduce**
While running strawberry, open any other media application. (vlc, chrome or even gwenview).
At first applet run normally, can control strawberry, both applications (strawberry and vlc for example) are shown on its combo box.
Quit the other application while strawberry is still running.
Media player applet is no longer shown on system tray.
When you run any media app again, applet is shown, can control strawberry.
Applet is hidden again when you close other app, which is reproducible.

**Expected behavior**
Media player applet should still be shown after other media apps quit.

**System Information:**
 - Operating system: opensuse 15.2
 - Strawberry Version: 0.8.2 from opensuse update repository

**Additional context**
I see this same behavior on two different systems.

**Comment by jonaski** [comment] 2020-10-22 15:41
I can't reproduce this on openSUSE thumbleweed. I tried to open VLC and close it, the media applet stays open when strawberry is open.
I doubt this is a bug in Strawberry, perhaps something that is already fixed in KDE?

**Comment by yavuzmert** [comment] 2020-10-22 22:51
Hi Jonas,
After you said that you cannot reproduce this, i ran a live tumbleweed iso on virtualbox, installed strawberry on it, and you are right, no problem there.
Then i tried same with opensuse 15.2 kde live iso, but no problem there either.
So i thought it may be because of a garbage configuration from a previous version on my desktop. I removed "~/.config/strawberry" and "~/.local/share/strawberry". But no, problem persists on my system. So it may be because of an update on opensuse 15.2 or totally specific to my systems.
Anyway this is just a minor annoyance; so, if you guide me to check some other place i can try to find the cause of the problem, otherwise you can ignore this, I will live with it.
Thanks

**Comment by jonaski** [comment] 2020-10-23 16:14
Then create a temporary user account, login in with that and check if you have the same problem, if not I suggest to delete kde/plasma specific cache and configuration files under ~/.cache/ and ~/.config/, but do it when logged out

**Comment by yavuzmert** [comment] 2020-10-24 11:13
Hi Jonas,
I found under which conditions this problem occurs. I tested using live ISO's, so not about my system, plasma configuration etc.
It is seen on opensuse 15.2, not tumbleweed. So we can think it as an already resolved plasma problem, but it is triggered by plasma logout when strawberry running, so maybe you can have a look at that to prevent this or any other side effects.
This is really a strange problem which is seen with a specific configuration and workflow, you won't reproduce this at all if "Keep running in the background.." option in strawberry settings is not selected.

To reproduce the problem:
- Log on to plasma session
- Open strawberry, everything works as expected, media player shortcuts can play/pause strawberry, applet is shown at system tray.
- Select "Keep running in the background.." option in settings, if not already.
- Try to logout
    - If strawberry window is shown plasma cannot logout. **This is both on 15.2 and tumbleweed. This may need a seperate bug report.**
![Screenshot_20201024_011406](https://user-images.githubusercontent.com/19837772/97078167-c6697100-15f2-11eb-9b9f-46ef2b69f6dc.png)

    - If strawberry is closed to system tray, plasma can logout

- Logon again to plasma, strawberry is started automatically by plasma session
- But this time media player shortcuts do not start playing strawberry
- If you run vlc (or any other media app), media player applet is shown, applet controls strawberry
- After you close vlc, media player applet is hidden as I described previously

By the way, clementine does not have this problem.

**Comment by jonaski** [comment] 2020-10-24 12:09
I'll have a look at the logout thing again.

**Closed** 2020-10-25 19:00 UTC
