### ISSUE TITLE
Freeze when attempting to access systemd managed disconnected external device

### ISSUE THREAD

**Issue by DAMO238** [strawberrymusicplayer/strawberry#410] opened 2020-04-20 15:36 UTC
**Describe the bug**
When strawberry tries to change song, it stops drawing the window and the system tray icon cannot be interacted with. When running in terminal, you get this output during the crash:

```
16:18:14.745 DEBUG PlaylistBackend:332              Saving playlist 18
16:18:16.601 ERROR logging:71(GLib)                 Source ID 24 was not found when attempting to remove it
Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.UDisks2VolumeMonitor: Timeout was reached (g-io-error-quark, 24)
16:18:26.011 INFO  DeviceManager:455                Device added: "Gio//btrfs/119535599616" ("Gio//btrfs/119535599616")
16:18:26.012 INFO  DeviceManager:455                Device added: "Gio//msdos/305569792" ("Gio//btrfs/119535599616", "Gio//msdos/305569792")
16:18:26.013 INFO  DeviceManager:455                Device added: "Gio//btrfs/1000203816960" ("Gio//btrfs/1000203816960", "Gio//btrfs/119535599616", "Gio//msdos/305569792")
16:19:13.600 DEBUG Database:487                     Starting database integrity check
16:19:13.611 DEBUG Database:548                     Starting database backup
16:20:01.286 WARN  GioLister::DeviceInfo:453        Error getting filesystem info for /home/damien/Games: No such device
16:20:01.286 INFO  DeviceManager:455                Device added: "Gio///0" ("Gio///0", "Gio//btrfs/1000203816960", "Gio//btrfs/119535599616", "Gio//msdos/305569792")

```

**To Reproduce**
Use an external drive with the following fstab (specifically the last entry, but I pasted the entire thing in case it is something else):
```
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
# /dev/sdb1 LABEL=root
UUID=2a72b552-9914-4bc4-90b7-7cae42309be7	/         	btrfs     	rw,nodev,relatime,ssd,discard,space_cache,subvolid=256,subvol=/__current/root,subvol=__current/root	0 0
UUID=2a72b552-9914-4bc4-90b7-7cae42309be7	/run/btrfs-root         	btrfs     	rw,nodev,relatime,ssd,discard,space_cache,nosuid,noexec	0 0

# /dev/sdb2
UUID=E445-38E7      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro	0 2

# /dev/sda1 LABEL=home
UUID=bd613623-579e-4117-9a51-62a05ab8af0e	/home     	btrfs     	rw,nodev,relatime,ssd,discard,space_cache,subvolid=257,subvol=/__current/home,subvol=__current/home	0 0
UUID=bd613623-579e-4117-9a51-62a05ab8af0e	/run/btrfs-home     	btrfs     	rw,nodev,relatime,ssd,discard,space_cache,nosuid,noexec	0 0

# /dev/sdb3
UUID=f69f09b0-76d0-4d63-b838-6d6b078cf5ab	none      	swap      	defaults  	0 0

# /dev/sdc1
UUID=6e80b340-52a3-4a52-a7f1-11ac2feabd1a       /home/damien/Games      ext4    rw,user,exec,noauto,x-systemd.automount,x-systemd.device-timeout=1min,nofail 0 2
```

**Expected behavior**
After trying to access device and failing, carry on playing other songs from onboard drive (where all my songs are anyway).

**System Information:**
 - Operating system: Arch (kernel: 5.6.4-arch1-1)
 - Strawberry Version: strawberry 0.6.9-1

**Additional context**
Works perfectly after plugging back in the external hard drive as systemd mounts it on access.

**Comment by jonaski** [comment] 2020-04-20 17:05
I don't see any crash in any of your pasted logs. But you mention that the UI can't be interacted with, that means the program freezes, in that case it's not a crash.
Do you add the file directly from the drive, add a folder to the collection, or do you access it in devices?
Do you play a song located on the device while disconnecting?
Do you unmount the device before disconnecting it?
In any case where you disconnect the drive while playing a song from the drive, it's gstreamer engine that's causing the freeze, it can't be fixed by changing anything in Strawberry.
Unmounting the drive while playing won't work because of file access.

**Comment by DAMO238** [comment] 2020-04-21 15:26
Yes, it was a freeze. The problem is that the drive was not connected, but the mount point still exists, so accessing will cause systemd to try to mount it (see the systemd automount options) and fails because it is not connected. I did not try to access it from strawberry, it just tried to do it automatically when switching songs in the playlist. There are no songs even on the drive.

**Comment by jonaski** [comment] 2020-04-24 18:06
I see. Well we are not doing anything directly that should something like that, so my guess is that it's one of the libraries we use, or something low-level.

**Comment by WGH-** [comment] 2022-01-06 03:27
I have somewhat similar setup with systemd automounting configured for my NAS, which is sometimes inaccessible, and thus causes annoying UI freezes, not to mention unwanted network activity.

I believe the problem is here:

https://github.com/strawberrymusicplayer/strawberry/blob/ea2bfbda44f2f76cfda4ba483497c648ec62876a/src/device/giolister.cpp#L471

Trying to get filesystem free size, etc. is certainly something that triggers automounting.

**Comment by WGH-** [comment] 2022-01-08 20:56
`df`, for example, does not trigger automounting, but `df --all` does. It has special cases for certain filesystem types, which it considers "dummy". This does look pretty ugly, I have to admit.

https://github.com/coreutils/coreutils/blob/73bd6306d16c325cd5641b11405bef59b2d75ad9/src/df.c#L756-L763
```c
      /* Avoid stating remote file systems as that may hang.
         On Linux we probably have me_dev populated from /proc/self/mountinfo,
         however we still stat() in case another device was mounted later.  */
      if ((me->me_remote && show_local_fs)
          || (me->me_dummy && !show_all_fs && !show_listed_fs)
          || (!selected_fstype (me->me_type) || excluded_fstype (me->me_type))
          || -1 == stat (me->me_mountdir, &buf))
        {
```

https://github.com/coreutils/gnulib/blob/549fce0183f02d5f4253cf18bfc2bbd82f0b1783/lib/mountlist.c#L164-L194
```c
#define ME_DUMMY_0(Fs_name, Fs_type)            \
  (strcmp (Fs_type, "autofs") == 0              \
   || strcmp (Fs_type, "proc") == 0             \
   || strcmp (Fs_type, "subfs") == 0            \
   /* for Linux 2.6/3.x */                      \
   || strcmp (Fs_type, "debugfs") == 0          \
   || strcmp (Fs_type, "devpts") == 0           \
   || strcmp (Fs_type, "fusectl") == 0          \
   || strcmp (Fs_type, "fuse.portal") == 0      \
   || strcmp (Fs_type, "mqueue") == 0           \
   || strcmp (Fs_type, "rpc_pipefs") == 0       \
   || strcmp (Fs_type, "sysfs") == 0            \
   /* FreeBSD, Linux 2.4 */                     \
   || strcmp (Fs_type, "devfs") == 0            \
   /* for NetBSD 3.0 */                         \
   || strcmp (Fs_type, "kernfs") == 0           \
   /* for Irix 6.5 */                           \
   || strcmp (Fs_type, "ignore") == 0)

/* Historically, we have marked as "dummy" any file system of type "none",
   but now that programs like du need to know about bind-mounted directories,
   we grant an exception to any with "bind" in its list of mount options.
   I.e., those are *not* dummy entries.  */
#ifdef MOUNTED_GETMNTENT1
# define ME_DUMMY(Fs_name, Fs_type, Bind)	\
  (ME_DUMMY_0 (Fs_name, Fs_type)		\
   || (strcmp (Fs_type, "none") == 0 && !Bind))
#else
# define ME_DUMMY(Fs_name, Fs_type)		\
  (ME_DUMMY_0 (Fs_name, Fs_type) || strcmp (Fs_type, "none") == 0)
#endif
```

**Comment by WGH-** [comment] 2022-01-08 20:59
glib also has somewhat similar list, which is fortunately public and can be used through `g_unix_is_system_fs_type`:

https://github.com/GNOME/glib/blob/ae0ec9b7533d3d69a7207950d769e9eeea5d7e92/gio/gunixmounts.c#L308-L360
```c
gboolean
g_unix_is_system_fs_type (const char *fs_type)
{
  const char *ignore_fs[] = {
    "adfs",
    "afs",
    "auto",
    "autofs",
    "autofs4",
    "cgroup",
    "configfs",
    "cxfs",
    "debugfs",
    "devfs",
    "devpts",
    "devtmpfs",
    "ecryptfs",
    "fdescfs",
    "fusectl",
    "gfs",
    "gfs2",
    "gpfs",
    "hugetlbfs",
    "kernfs",
    "linprocfs",
    "linsysfs",
    "lustre",
    "lustre_lite",
    "mfs",
    "mqueue",
    "ncpfs",
    "nfsd",
    "nullfs",
    "ocfs2",
    "overlay",
    "proc",
    "procfs",
    "pstore",
    "ptyfs",
    "rootfs",
    "rpc_pipefs",
    "securityfs",
    "selinuxfs",
    "sysfs",
    "tmpfs",
    "usbfs",
    NULL
  };

  g_return_val_if_fail (fs_type != NULL && *fs_type != '\0', FALSE);

  return is_in (fs_type, ignore_fs);
}
```

I suppose Strawberry could use this function, as the list certainly looks good enough.

**Comment by jonaski** [comment] 2022-01-08 21:02
We should exclude network mounts.
Do you want to try a change and open a PR for it?

**Comment by WGH-** [comment] 2022-01-08 21:19
Yeah, I guess I could.

This is not really a problem with network mounts, however. If you had a network mount in `/etc/fstab`, it would simply be shown unmounted in the Devices tab, no harm done. If it is mounted, I guess Strawberry would attempt to query its statistics, but if it's already mounted, I believe it's also fine at this point.

The problem is specifically about autofs, as attempting to query its size triggers mounting of the actual filesystem.

**Closed** 2022-01-11 17:05 UTC
